### ISSUE TITLE
Custom route style(iOS)

### ISSUE THREAD

**Issue by AntonLunegovPerm** [yandex/mapkit-ios-demo#101]
Hello!
How I can set our custom route style (StrokeColor, StrokeColor, StrokeStyle) ?
I found some example for [JS](https://yandex.com/dev/maps/jsapi/doc/2.1/dg/concepts/router/multiRouter.html/). Can I repeat it in iOS app?

**Comment by eberkovich** [comment]
Hello,

There are  two  classes for displaying routes: [YMKColoredPolylineMapObject](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKColoredPolylineMapObject.html/) and YMKRouteHelper(unfortunately at this time it has [documentation](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/directions/driving/RouteHelper.html/) for android api only, but it is identical).


For example:
```
routePolyline = map.mapObjects.addColoredPolyline();
YMKRouteHelper.updatePolyline(withPolyline: routePolyline, route: route, style: YMKRouteHelper.createDefaultJamStyle());
```

Please keep in mind using YMKRouteHelper to setup YMKColoredPolyline is much more optimal than manually (using geometry from YMKDrivingRoute).

**Comment by AntonLunegovPerm** [comment]
Thank you!It's really helped me.
