### ISSUE TITLE
onMapLongTap на карте на ios 14.1 некорректно работает

### ISSUE THREAD

**Issue by ufsergey** [yandex/mapkit-ios-demo#103]
На  iOS 14.1 постоянно срабатывает событие -(void)onMapLongTapWithMap:(YMKMap *)map point:(YMKPoint *)point, хотя нет долгого нажатия на карту, только обычные свайпы одним пальцем для скролла карты. На iOS 13 и более ранних версиях долгое нажатие работает корректно.

**Comment by eberkovich** [comment]
Эта проблема исправлена в последней версии mapkit=4.0.0
