### ISSUE TITLE
Как задать позицию пользователя как в Яндекс Go (Такси)

### ISSUE THREAD

**Issue by zhukov-n** [yandex/mapkit-ios-demo#105]
Как с помощью Yandex-map-kit можно реализовать экран как в Яндекс Go?

![Screenshot 2021-02-09 at 13 28 35](https://user-images.githubusercontent.com/69805931/107344634-1c97ec80-6adc-11eb-83ef-c15143ffb017.png)

Карта должна иметь пин (позицию пользователя) по центру карты (смешена немного вверх). При скроле этот пин перемещается. Также нужна возможность понять это позицию в геокоординатах.

Пока вижу 2 решения и оба кажутся "не очень":

1. Использовать `YMKPlacemarkMapObject` и перемешать его используя `YMKMapCameraListener` и его `YMKCameraPosition`. Тут 2 проблемы:

- `YMKMapCameraListener` использует под капотом оптимизации, в результате при скроле пин немного запаздывает и смещается относительно центра карты
- Магия с вычислением смещения по вертикали, чтобы пин находился чуть выше центра карты

2. Пин вынести из карты совсем и просто положить как отдельный UIView на карту. Тут начинается пляска с расчетом позиции под пином

**Comment by IvanUshakov** [comment]
Делал смещение пина. Для этого можно использовать у YMKMapWindow проперти focusRect
