### ISSUE TITLE
Ошибка при сборке на ARM-симулятор на MacBook c процессором M1

### ISSUE THREAD

**Issue by vani2** [yandex/mapkit-ios-demo#106]
Установка

```
pod 'YandexMapsMobile', '4.0.0-full'

pod --version
1.10.1
```

Ошибка 

```
ld: in /Users/user/Documents/Xcode/project-ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/user/Documents/Xcode/project-ios/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64
```

**Comment by maksimgromov** [comment]
Нашли решение проблемы?

**Comment by vani2** [comment]
@maksimgromov собираем на девайс или под Rosetta.

**Comment by maksimgromov** [comment]
Спасибо за помощь!

**Comment by nugmanoff** [comment]
есть в планах поддержать М1 из коробки без Rosetta?

**Comment by CBBBrother** [comment]
> есть в планах поддержать М1 из коробки без Rosetta?

Да, работаем сейчас над этим.

**Comment by Dominnik** [comment]
Мы до сих пор ставим версию 4.0.0?

**Comment by Ewg777** [comment]
@CBBBrother когда ожидать? Подскажите, пожалуйста

**Comment by OlegEremenko991** [comment]
> > есть в планах поддержать М1 из коробки без Rosetta?
> 
> Да, работаем сейчас над этим.

Скажите пожалуйста, когда планируете выпустить релиз с поддержкой M1 из коробки?

**Comment by Rabbit13245** [comment]
> > есть в планах поддержать М1 из коробки без Rosetta?
> 
> Да, работаем сейчас над этим.

Тоже очень интересует вопрос, когда будет релиз с поддержкой м1 из коробки

**Comment by debug45** [comment]
Аналогично, на M1 Max проект не собрать

**Comment by navartis** [comment]
> > > есть в планах поддержать М1 из коробки без Rosetta?
> > 
> > 
> > Да, работаем сейчас над этим.
> 
> Тоже очень интересует вопрос, когда будет релиз с поддержкой м1 из коробки

Плюсую.

Ну когда уже завезут поддержку M1?!

Негодую

**Comment by CBBBrother** [comment]
Добавили поддержку M1, осталось дождать публичного релиза.

**Comment by Rabbit13245** [comment]
> Добавили поддержку M1, осталось дождаться публичного релиза.

А сколько ждать релиза примерно? 
надеюсь не год 😊

**Comment by Rabbit13245** [comment]
А есть какие-то новости с релизом М1?

**Comment by evgeniy-ryadovoy** [comment]
Where is release, Lebowski? (c)
Очень очень ждем ;)

**Comment by echoechoechoechoechoecho** [comment]
Xcode 13.3 - больше не собирается на живое устройство :)

`ld: in /Users/user/Documents/projects/project/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKLogo_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file '/Users/user/Documents/projects/project/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64`

**Comment by Dodecaidr** [comment]
ну у меня на устройство собирает, но а вот fastlane нет и падает с такой же ошибкой:
ld: in ..Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file '../Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64

**Comment by Dodecaidr** [comment]
на устройстве тоже перестало собираться) Я перепроверил

**Comment by tima5959** [comment]
Xcode 13.3 не работает ни симулятор ни реальное устройство
Xcode 12.1 не работает симулятор

**Comment by Rabbit13245** [comment]
плюсую. На девайс Яндекс карты не собираются на м1. 
Xcode 13.3, в настройках проекта стоит excluded archs arm64.

**Comment by debug45** [comment]
Раньше на M1 Max юзал запуск Xcode через Rosetta, и всё собиралось — даже для симуляторов. Теперь вообще никак и ни для чего не билдится.

**Comment by pablokhmel** [comment]
Не запускается на реальном устройстве. Нашли решение уже?

**Comment by navartis** [comment]
Архивация проекта тоже фейлится

**Comment by navartis** [comment]
@CBBBrother Хьюстон, у нас проблемы!

Алярм

**Comment by Dominnik** [comment]
> Архивация проекта тоже фейлится

Ну архивация это тот же билл

**Comment by navartis** [comment]
> Ну архивация это тот же билл

Но архивация != билд

**Comment by debug45** [comment]
Стало снова собираться после того, как в системных настройках macOS установил свежее обновление «Command Line Tools»

**Comment by Rabbit13245** [comment]
> Стало снова собираться после того, как в системных настройках macOS установил свежее обновление «Command Line Tools»

Какая версия теперь стоит?

**Comment by Dodecaidr** [comment]
Я просто поставил предыдущий Xcode и Command Line Tools для него

**Comment by Dodecaidr** [comment]
Я просто поставил предыдущий Xcode и Command Line Tools для него. И все начало работать

**Comment by Rabbit13245** [comment]
> Я просто поставил предыдущий Xcode и Command Line Tools для него. И все начало работать

ну то есть Xcode 13.2.1? 
Если да, то на нем и так все прекрасно собиралось

**Comment by Dodecaidr** [comment]
> > Я просто поставил предыдущий Xcode и Command Line Tools для него. И все начало работать
> 
> ну то есть Xcode 13.2.1? Если да, то на нем и так все прекрасно собиралось

Да и сейчас уже начал наверстывать вчерашнии задачки))

**Comment by Rabbit13245** [comment]
> > > Я просто поставил предыдущий Xcode и Command Line Tools для него. И все начало работать
> > 
> > 
> > ну то есть Xcode 13.2.1? Если да, то на нем и так все прекрасно собиралось
> 
> Да и сейчас уже начал наверстывать вчерашнии задачки))

Речь-то идет именно о сборке на Xcode 13.3...😐

**Comment by Dodecaidr** [comment]
> > > > Я просто поставил предыдущий Xcode и Command Line Tools для него. И все начало работать
> > > 
> > > 
> > > ну то есть Xcode 13.2.1? Если да, то на нем и так все прекрасно собиралось
> > 
> > 
> > Да и сейчас уже начал наверстывать вчерашнии задачки))
> 
> Речь-то идет именно о сборке на Xcode 13.3...😐

Это понятно, но когда работа встала, надо же, что то делать.  Кому-то это может быть быстрым выходом из этой ситуевины

**Comment by Rabbit13245** [comment]
> > > > > Я просто поставил предыдущий Xcode и Command Line Tools для него. И все начало работать
> > > > 
> > > > 
> > > > ну то есть Xcode 13.2.1? Если да, то на нем и так все прекрасно собиралось
> > > 
> > > 
> > > Да и сейчас уже начал наверстывать вчерашнии задачки))
> > 
> > 
> > Речь-то идет именно о сборке на Xcode 13.3...😐
> 
> Это понятно, но когда работа встала, надо же, что то делать. Кому-то это может быть быстрым выходом из этой ситуевины

Быстрый выход - не обновлять бездумно софт на последнюю версию😜

**Comment by navartis** [comment]
> > > > > > Я просто поставил предыдущий Xcode и Command Line Tools для него. И все начало работать
> > > > > 
> > > > > 
> > > > > ну то есть Xcode 13.2.1? Если да, то на нем и так все прекрасно собиралось
> > > > 
> > > > 
> > > > Да и сейчас уже начал наверстывать вчерашнии задачки))
> > > 
> > > 
> > > Речь-то идет именно о сборке на Xcode 13.3...😐
> > 
> > 
> > Это понятно, но когда работа встала, надо же, что то делать. Кому-то это может быть быстрым выходом из этой ситуевины
> 
> Быстрый выход - не обновлять бездумно софт на последнюю версию😜

Аааааа 
Да зачем вообще обновлять что то и пилить фичи в свои проекты))))

Надо брать пример с Yandex - ничего не обновлять и никаких фичей не пилить)))))

**Comment by navartis** [comment]
Я вообще молчу что за этот сервис Yandex деньги берет и не малые

**Comment by ivanglushko** [comment]
Xcode 13.3 M1 Pro - траблы такие же с запуском на девайсе :(

**Comment by fedorinovdmitry** [comment]
Присоединяюсь к проблеме, Xcode 13.3, intel i9, не собирается на реальном девайсе.
in /Users/skinnerimac/DeveloperProjectIMac/El Mashine/qa 3 2/Products/Gold585/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKRouteView_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file '/Users/skinnerimac/DeveloperProjectIMac/El Mashine/qa 3 2/Products/Gold585/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64

**Comment by echoechoechoechoechoecho** [comment]
Цитирую ответ поддержки:

> Разработчики ответили, что текущий публичный релиз Mapkit не собирается на Xcode 13.3.
> 
> Сейчас готовится обновление Mapkit, в нем уже должна будет появиться поддержка Xcode 13.3.
> К сожалению, по срокам выхода обновлений пока не смогу ответить.

Видимо, придётся пока посидеть на 13.2.1 :)

**Comment by Ewg777** [comment]
> Цитирую ответ поддержки:
> 
> > Разработчики ответили, что текущий публичный релиз Mapkit не собирается на Xcode 13.3.
> > Сейчас готовится обновление Mapkit, в нем уже должна будет появиться поддержка Xcode 13.3.
> > К сожалению, по срокам выхода обновлений пока не смогу ответить.
> 
> Видимо, придётся пока посидеть на 13.2.1 :)

Железный занавес пришел откуда не ждали

**Comment by debug45** [comment]
> Цитирую ответ поддержки:
> 
> > Разработчики ответили, что текущий публичный релиз Mapkit не собирается на Xcode 13.3.
> > Сейчас готовится обновление Mapkit, в нем уже должна будет появиться поддержка Xcode 13.3.
> > К сожалению, по срокам выхода обновлений пока не смогу ответить.
> 
> Видимо, придётся пока посидеть на 13.2.1 :)

Возникает вопрос, зачем тогда Apple выпускает кучу публичных бета-версий в течение пары месяцев перед каждым платформенным релизом, если разработчики столь крупных сервисов как Яндекс всё это игнорируют и никак к обновлениям iOS/Xcode заранее не готовятся

**Comment by thematver** [comment]
Я удивлен, что это еще не решилось

**Comment by CBBBrother** [comment]
Проблему решили, осталось зарелизить наружу.

**Comment by tima5959** [comment]
> Проблему решили, осталось зарелизить наружу.

Есть примерные сроки релиза?

**Comment by Roman-Kerimov** [comment]
> Есть примерные сроки релиза?
Видимо, где‐то ещё через год или два

**Comment by Ramiz69** [comment]
> > Есть примерные сроки релиза?
> 
> Видимо, где‐то ещё через год или два

Перед этим личные данные пользователей сольет

**Comment by Nyakit** [comment]
Бедная контора Яндекс, нет 1 бедолаги для фикса хотя бы 1 issue из огромного списка. Пойду собес в яндекс проходить, чтоб закрыть этот баг и вернусь на свои проекты

**Comment by AlexanderNaumov** [comment]
Похоже на документацию и баги не хватило бюджета)

**Comment by AndreyKrivopalov** [comment]
Дело в xcode

**Comment by remakerich** [comment]
> Дело в xcode

тоесть на м1 уже работает?
а какой xcode должен быть не подскажете?

**Comment by AndreyKrivopalov** [comment]
> > Дело в xcode
> 
> тоесть на м1 уже работает? а какой xcode должен быть не подскажете?

На m1 не могу сказать, но работает точно на xcode 13.2.1

**Comment by remakerich** [comment]
> > > Дело в xcode
> > 
> > 
> > тоесть на м1 уже работает? а какой xcode должен быть не подскажете?
> 
> На m1 не могу сказать, но работает точно на xcode 13.2.1

Благодарю, буду пробовать

**Comment by FeofanGreek** [comment]
Им похоже никак в  cocoapods не проапрувят новый дистрибутив (ИМХО санкции). Под эмуляторы билдим убирая из архитектур arm64 и оставляем только  armv7... это я за тех говорю, кто на любом из M1... эмулятор розетту юзает чтоб запуститься. А вот нормальный билд, даже на живой айфон по шнурку, уже не сделать, надо ставить arm64 и в результате ошибка.

**Comment by remakerich** [comment]
А никто не в курсе почему карту в симуляторе так колбасит жеско? чуть чуть сдвигаешь и она улетает на другой конец земного шара... это тоже косяки сборки?

**Comment by FeofanGreek** [comment]
Есть там такой косяк. Что то с эмулятором. На реальных устройствах все ок было, когда работало.

**Comment by remakerich** [comment]
Так, есть небольшая инфа (может не новость уже, но все равно кто то может до сих пор не может решить проблему)

1. у меня M1
2. Xcode 13.2.1

Дебажится нормально **только на реальном девайсе**
Симулятор по прежнему отказывается работать (предположительно изза М1)

**Comment by OlegEremenko991** [comment]
> Так, есть небольшая инфа (может не новость уже, но все равно кто то может до сих пор не может решить проблему)
> 
> 
> 
> 1. у меня M1
> 
> 2. Xcode 13.2.1
> 
> 
> 
> Дебажится нормально **только на реальном девайсе**
> 
> Симулятор по прежнему отказывается работать (предположительно изза М1)

Все так, используем такой подход уже год.
Очень ждём релиза с поддержкой М1

**Comment by FeofanGreek** [comment]
ну год не обновляться... это же жесть. уже и ИОС другая и айфоны новые

**Comment by ygboy1986** [comment]
Xcode 13.3 also has the same error, is there any solution?

![image](https://user-images.githubusercontent.com/8225211/163365512-a157d5a8-303c-4734-a395-fffcb1fd8358.png)

**Comment by remakerich** [comment]
> 

13.2.1

**Comment by Ramiz69** [comment]
> Xcode 13.3 also has the same error, is there any solution?
> 
> ![image](https://user-images.githubusercontent.com/8225211/163365512-a157d5a8-303c-4734-a395-fffcb1fd8358.png)

Use Xcode 13.2.1. Yandex is in no hurry to update or use Google maps(better)

**Comment by ygboy1986** [comment]
> > Xcode 13.3 也出现同样的错误，请问有什么解决办法吗？
> > ![图片](https://user-images.githubusercontent.com/8225211/163365512-a157d5a8-303c-4734-a395-fffcb1fd8358.png)
> 
> 使用 Xcode 13.2.1。Yandex 不急于更新或使用谷歌地图（更好）

Thanks, I will try.

**Comment by Roman-Kerimov** [comment]
> Им похоже никак в cocoapods не проапрувят новый дистрибутив (ИМХО санкции).

Так пусть на Swift PM наконец‐то перейдут

**Comment by isc4** [comment]
Залили бы уже правки в свой репозиторий

**Comment by Kuda-ob84** [comment]
Найс, а как быть людям которые обновились до iOS 15.4 который не работает на XCode 13.2.1? Хоть убей не запускается на XCode 13.3, даже с последней обновой

**Comment by VNGXR** [comment]
> Найс, а как быть людям которые обновились до iOS 15.4 который не работает на XCode 13.2.1? Хоть убей не запускается на XCode 13.3, даже с последней обновой
> 
> 

Можно DeviceSupport от 13.3 закинуть в 13.2.1.
Собственно я так и пользуюсь 13.2.1

**Comment by isc4** [comment]
> > Найс, а как были люди, которые обновились до iOS 15.4, которая не работает на XCode 13.2.1? Хоть убейте не использовать на XCode 13.3, даже с последней обновой
> 
> Можно DeviceSupport из 13.3 закинуть в 13.2.1. Собственно я так и пользуюсь 13.2.1

Спасибо за информацию! Вот ссылка, может кому пригодится: https://medium.com/@nayananp/how-to-add-device-support-files-to-xcode-4a7609b2f534

**Comment by DurnevY** [comment]
Господа, это уже не серьезно. Вы дайте хоть какую-то инфу. Что ни SDK от вас, то боль и страдания. Что вы там делаете? На листочке пишите фикс? Бросьте вы уже это дело, используйте клаву.

**Comment by akonoplev** [comment]
Что по поддержке библиотеки в Xcode 13.3?
Не собирается под реальное устройство 

ld: in /Users/ak/Desktop/ios-app/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile(YMKLogo_Binding.mm.o), section __DATA/__bss has type zero-fill but non-zero file offset file '/Users/ak/Desktop/ios-app/Pods/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile' for architecture arm64

**Comment by debug45** [comment]
Мда, просто позорище какое-то...

**Comment by toure20** [comment]
Господа, поставьте в приоритет..

**Comment by iMrOwl** [comment]
Вы бы хоты бы сроки сказали...

**Comment by Ewg777** [comment]
как квиксорт перепишут, сразу сольют

**Comment by nabiullin** [comment]
Да грустно, проект архивнуть даже не можем сейчас...

**Comment by maksimgromov** [comment]
> Да грустно, проект архивнуть даже не можем сейчас...

Да откатите XCode, и спокойно все соберется

**Comment by debug45** [comment]
> Да откатите XCode, и спокойно все соберется

Очень надеюсь, что вы не в Яндексе работаете 😄

**Comment by FeofanGreek** [comment]
Яндекс того не стоит

**Comment by FeofanGreek** [comment]
НОКИЯ 3110 и журнал с рингтонами

**Comment by YaphetS1** [comment]
Common ребят, это уже не серьезно... Первая бета вышла 27 Янв 2022, сколько с того момента прошло?
По поводу сборки на эмуляторе под симулятор для М1, я молчу...

Что за ерунда? Нехватка кадров? Ресурсов? Чего? Что мешает поправить пару (десятков) инструкций? И пересобрать это дело?

Мы все надеемся на скорый фикс! ASAP 👀

**Comment by maksimgromov** [comment]
> Common ребят, это уже не серьезно... Первая бета вышла 27 Янв 2022, сколько с того момента прошло? По поводу сборки на эмуляторе под симулятор для М1, я молчу...
> 
> Что за ерунда? Нехватка кадров? Ресурсов? Чего? Что мешает поправить пару (десятков) инструкций? И пересобрать это дело?
> 
> Мы все надеемся на скорый фикс! ASAP 👀

Что за коммон ребята?

**Comment by toure20** [comment]
> > Common ребят, это уже не серьезно... Первая бета вышла 27 Янв 2022, сколько с того момента прошло? По поводу сборки на эмуляторе под симулятор для М1, я молчу...
> > Что за ерунда? Нехватка кадров? Ресурсов? Чего? Что мешает поправить пару (десятков) инструкций? И пересобрать это дело?
> > Мы все надеемся на скорый фикс! ASAP 👀
> 
> Что за коммон ребята?

Иными словами просит их поднажать немного) Мы откатили xcode на 13.2.1 и так живем, и будем жить думаю еще долго)

**Comment by GazizovRuslan** [comment]
Коллеги сообщили, что релиз MapKit с поддержкой процессоров М1 планируется на следующей неделе.
maps-api@support.yandex.ru

**Comment by c-villain** [comment]
Если кому надо, вот [версия](https://github.com/c-villain/YandexMapsMobile), работающая на Xcode > 13.3 в режиме Розетты, собирается как на девайс, так и на симулятор... 
а так, ждем полноценного релиза на M1 🎉

**Comment by igor-makarov** [comment]
The version added here by @c-villain was made using a hacked build of my `xcframework_converter` (https://github.com/igor-makarov/XCFrameworkConverter) that I've put together.

It's a very complex hack so I won't be releasing it as an official version on RubyGems.

Here's the link to the gem build for anyone who needs it: https://github.com/igor-makarov/XCFrameworkConverter/releases/tag/0.4.0-hack-zerofill  
Download the gem build directly from the release page as it isn't published.

You can use it with your CocoaPods setup directly to patch the Yandex SDK during install by following the instructions.

**Comment by Roman-Kerimov** [comment]
> Коллеги сообщили, что релиз MapKit с поддержкой процессоров М1 планируется на следующей неделе.
> [maps-api@support.yandex.ru](mailto:maps-api@support.yandex.ru)

Сегодня последний рабочий день этой самой следующей недели. Релиз сегодня?

**Comment by protuberian** [comment]
> Сегодня последний рабочий день этой самой следующей недели. Релиз сегодня?

Держи карман шире!

**Comment by Roman-Kerimov** [comment]
> Держи карман шире!

Мне вот уже даже интересно, если Яндекс бы меня нанял, чтобы переписать это их поделие с Objective‐C на Swift, чтоб всё это через SPM нормально работало и всё с нормальной типизацией было, а не с NSNumber в kinds в компоненте адреса, то я быстрее бы справился, чем они этот апдейт выкатят, или всё‐таки нет.

Но за полтора года с момента релиза M1 точно уж стоило бы всё переписать — было б дешевле и быстрее

**Comment by igor-makarov** [comment]
You know this SDK is written in C++ and has half of the C++ ecosystem inside it?

**Comment by OlegEremenko991** [comment]
В яндексе решается судьба компании, а мы тут ждем релиза какой-то там либы

**Comment by DurnevY** [comment]
> В яндексе решается судьба компании, а мы тут ждем релиза какой-то там либы

1. Как в этом задействованы разрабочики?
2. С такими темпами итог предсказуем.

**Comment by OlegEremenko991** [comment]
> > В яндексе решается судьба компании, а мы тут ждем релиза какой-то там либы
> 
> 1. Как в этом задействованы разрабочики?
> 2. С такими темпами итог предсказуем.

Возможно, у менеджеров пожар, и возможно они дают разработчикам "более важные" задачи.
Но мы-то знаем, в чем дело.

**Comment by iMrOwl** [comment]
они вроде бабки берут за это)

**Comment by debug45** [comment]
Уже и Xcode 13.4 сегодня вышел, а воз и ныне там...

**Comment by krasmikes** [comment]
> А никто не в курсе почему карту в симуляторе так колбасит жеско? чуть чуть сдвигаешь и она улетает на другой конец земного шара... это тоже косяки сборки? (на андроиде то же самое приложение все четко)

Если еще актуально - попробуй симулятор через розетту запустить - мне помогло

**Comment by Dominnik** [comment]
> > А никто не в курсе почему карту в симуляторе так колбасит жеско? чуть чуть сдвигаешь и она улетает на другой конец земного шара... это тоже косяки сборки? (на андроиде то же самое приложение все четко)
> 
> Если еще актуально - попробуй симулятор через розетту запустить - мне помогло

Топик собственно и создавался для того, чтоб на М1 отказаться от розетты

**Comment by Roman-Kerimov** [comment]
> Топик собственно и создавался для того, чтоб на М1 отказаться от розетты

Но пока только отказались от новых версий Xcode

**Comment by alexeybolv** [comment]
Кто-нибудь знает, в 4.1.0 это закрыли?

**Comment by Kodryan** [comment]
> Кто-нибудь знает, в 4.1.0 это закрыли?

Кажется да, на м1 с 13.3 Xcode собирается на симулятор и девайс

**Comment by artur4** [comment]
> CocoaPods could not find compatible versions for pod 'YandexMapsMobile', '4.1.0-full'

platform :ios, '12.0'

**Comment by isc4** [comment]
> CocoaPods could not find compatible versions for pod 'YandexMapsMobile', '4.1.0-full'

pod install --repo-update

**Comment by krakatoor** [comment]
'cyclone' is not a recognized processor for this target (ignoring processor)

**Comment by CBBBrother** [comment]
> На симуляторе крашится с ошибкой 'cyclone' is not a recognized processor for this target (ignoring processor). А на девайсе клетчатая сетка вместо карты. Яндекс молодцы!

На симуляторе при создании YMKMapView передавайте параметр vulkanPreferred = true

**Comment by iMrOwl** [comment]
ну шо народ, взлетело)? яКарты молодцы?)

**Comment by krakatoor** [comment]
> vulkanPreferred

@property (nonatomic, readonly) BOOL vulkanPreferred

**Comment by ivanglushko** [comment]
Боже это тред будет вечно актуальный 🤬🥲

**Comment by krakatoor** [comment]
> > > vulkanPreferred
> > 
> > 
> > @Property (nonatomic, readonly) BOOL vulkanPreferred
> 
> * (id)initWithFrame:(CGRect)frame vulkanPreferred:(BOOL)vulkanPreferred;

Спасибо. Помогло.
Подтверждаю - на m1 в XCode 13.3.1 все работает.

**Comment by Kolch** [comment]
При переходе на 4.1.0 столкнулся с такой проблемой
https://github.com/yandex/mapkit-ios-demo/issues/144

**Comment by maksimgromov** [comment]
Подскажите, пожалуйста, у меня одного вместо карты отображается просто сетка (даже если вызывать с помощью YMKMapView.init(frame: .zero, vulkanPreferred: true))

**Comment by CBBBrother** [comment]
> Подскажите, пожалуйста, у меня одного вместо карты отображается просто сетка (даже если вызывать с помощью YMKMapView.init(frame: .zero, vulkanPreferred: true))?

Добавьте сюда https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/AppDelegate.swift#L25
YMKMapKit.sharedInstance()

Демо обновим в ближайшее время

**Comment by maksimgromov** [comment]
> > Подскажите, пожалуйста, у меня одного вместо карты отображается просто сетка (даже если вызывать с помощью YMKMapView.init(frame: .zero, vulkanPreferred: true))?
> 
> Добавьте сюда https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/AppDelegate.swift#L25 YMKMapKit.sharedInstance()
> 
> Демо обновим в ближайшее время

Спасибо!

**Comment by LexRS** [comment]
> > Подскажите, пожалуйста, у меня одного вместо карты отображается просто сетка (даже если вызывать с помощью YMKMapView.init(frame: .zero, vulkanPreferred: true))?
> 
> Добавьте сюда https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/AppDelegate.swift#L25 YMKMapKit.sharedInstance()
> 
> Демо обновим в ближайшее время

И в конструкторе прописал и .sharedInstance() инициализировал. На m1 в эмуляторе все равно "'cyclone' is not a recognized processor for this target (ignoring processor)"

**Comment by IHIierO** [comment]
> Подскажите пожалуйста. Я реализовал Мап Кит следующим кодом: struct Map: UIViewRepresentable {
> 
> ```
> func makeUIView(context: Context) -> YMKMapView {
>     
>     YMKMapKit.setApiKey("Мой ключ")
>     YMKMapKit.sharedInstance().onStart()
>     
>     
>     let mapView = YMKMapView(frame: .zero, vulkanPreferred: true)
>     
>     mapView?.mapWindow.map.move(
>             with: YMKCameraPosition.init(target: YMKPoint(latitude: 55.751574, longitude: 37.573856), zoom: 15, azimuth: 0, tilt: 0),
>             animationType: YMKAnimation(type: YMKAnimationType.smooth, duration: 5),
>             cameraCallback: nil)
>     
>     return mapView!
> 
>     
> }
> 
> func updateUIView(_ uiView: YMKMapView, context: Context) {
>     //
> } 
> ```
> 
> }
> 
> но в результате все равно отображается только сетка. Что я сделал не так?

Я тупой)) Допустил ошибку в своем ключе. В итоге этот метод вполне рабочий

**Comment by Nikita12G** [comment]
Добрый день. На мак м1 в симуляторе крату если попробовать скролить, то она солится бесконечно от одного касания. Есть ли решение данной проблемы? Кто-то сталкивался уже с подобным?

**Comment by Reeywhaar** [comment]
> Подскажите пожалуйста. Я реализовал Мап Кит следующим кодом: struct Map: UIViewRepresentable ...

> Добрый день. На мак м1 в симуляторе крату если попробовать скролить, то она солится бесконечно от одного касания. Есть ли решение данной проблемы? Кто-то сталкивался уже с подобным?

Как все это качается темы тикета?

**Comment by DanKamilov** [comment]
YandexMapKit error In PROJECT/Pods/YandexMapKit/YandexMapKit.framework/YandexMapKit(arrival_object_metadata.o), section __DATA/__bss has type zero-fill but non-zero file offset file 'PROJECT/Pods/YandexMapKit/YandexMapKit.framework/YandexMapKit' for architecture arm64

YandexMapKit 3.5.0
Xcode 14.2 

What to do???

**Comment by Lainaaa** [comment]
Xcode 15.1 
iOS 17.2
pod 'YandexMapsMobile', '4.5.1-lite'
**Errors:**
Framework 'YandexMapsMobile' not found
Linker command failed with exit code 1 (use -v to see invocation)

How to fix it?
