### ISSUE TITLE
Ограничить результаты suggestions 

### ISSUE THREAD

**Issue by iamalexantonov** [yandex/mapkit-ios-demo#107]
Добрый день, подскажите, пожалуйста, есть ли возможность ограничить результаты поиска suggestionItem до адреса, чтобы не было в результатах по фразе "Мичуринский проспект" метро Мичуринский проспект? И можно ли задать обязательные параметры ответа, например, только с номером дома?

Спасибо!

**Comment by elricbk** [comment]
Добрый день. Можно попробовать ограничить запрос только топонимами, тогда остановки должны пропасть. Другие ограничения задать нельзя, только фильтровать конечный результат. Фильтровать можно, например, по тегам. Но теги это просто строки и конкретные значения для них не гарантируются. 

<img src="https://user-images.githubusercontent.com/4334930/107480632-f16dd580-6b8d-11eb-9487-0b80213feaae.png" width="240">
