### ISSUE TITLE
Как добавить тень на YMKPlacemarkMapObject?

### ISSUE THREAD

**Issue by zhukov-n** [yandex/mapkit-ios-demo#108]
Необходимо добавить тень на пины объектов. Пины созадаю без использования картинок, через кастовый `UIView`.
```swift
let objectPinView = CustomView()
guard let viewProvider = YRTViewProvider(uiView: objectPinView) else { return }  
_ = map.mapObjects.addPlacemark(with: point, view: viewProvider)
```
Пин появляется на карте. Но его размеры ограничены фреймом. Если на него добавляем тень через слой то она отсекается.

Как можно легко добавить тень на пин, который создан через `YRTViewProvider(uiView: _)`?

**Comment by eberkovich** [comment]
А если objectPinView просто добавить в приложение он рисуется с тенью?

Так же пожалуйста имейте ввиду, что  ViewProvider автоматически не обновляется при изменении view, так что если после создания YRTViewProvider objectPinView был модифицирован , нужно явно позвать:

```
[viewProvider snapshot];
[placemarkMO setViewWithView:provider];
```
