### ISSUE TITLE
Анимация клстеризации пинов на карте 

### ISSUE THREAD

**Issue by donik** [yandex/mapkit-ios-demo#109]
collection.clusterPlacemarks(withClusterRadius: 60, minZoom: 15)

при добавлении новых точек обновляя кластеризацию пины начинают появляться с анимацией даже если они уже есть внутри кластера. Есть ли возможность отключить анимацию появления?

**Comment by cream-cheeze** [comment]
Да, я тоже, хотел бы уметь отключить анимацию - зачем мне нужно, чтобы все плейсмарки на карте моргали, если я просто заменил иконку всего у одного плейсмарка...
