### ISSUE TITLE
Как соединить линией placemark? Это вообще возможно?

### ISSUE THREAD

**Issue by dsenash** [yandex/mapkit-ios-demo#110]
Приветствую,
Так случилось, что у меня в приложении трек построился по placemark.
Может это и неправильно, но в первый момент это казалось простейшим путем.
И это прекрасно работало пока скорости передвижения были небольшие.
Потом при развитии приложения скорости увеличились и трек стал рваным.
Соответственно возник вопрос можно ли placemark соединить линиями?
Внимательно изучив документацию и факи я вообще не нашел никакого упоминания о такой возможности.
Соответственно вынужден вопрос задать здесь? Возможно это вообще или нет?
И если да, то в каком направлении копать?
Спасибо.

**Comment by eberkovich** [comment]
Здравствуйте, 
Не совсем понял, что значит "соединить placemark линиями", но mapkit позволяет соединить линиями точки с помощью [PolylineMapObject](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKPolylineMapObject.html) - для одноцветных линий, а также [ColoredPolylineMapObject](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKColoredPolylineMapObject.html) - для линий, отрезки которых могут быть раскрашены в разные цвета.
Пример можно посмотреть [здесь](https://github.com/yandex/mapkit-ios-demo/blob/e07ed0e05456b637c40e176a4a3d6fb53be1621c/MapKitDemo/MapObjectsViewController.swift#L93).

**Comment by dsenash** [comment]
Спасибо большое. Это как раз то что нужно.
