### ISSUE TITLE
версия 4.0.0-lite не работает на ios 9 и 10 . Ошибка symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by ufsergey** [yandex/mapkit-ios-demo#111]
ld: symbol(s) not found for architecture armv7 при сборке для ios старее чем 11. 
В документации сказано, что поддерживается 9. Какая минимальная версия ios нужна для 4.0.0-lite ?

**Comment by vlkigdm** [comment]
С версии 4.0.0 они удалили старые архитектуры armv7 и x86_64 (симуляторы с x86_64 тоже работать не будут).
Соответственно в таргетах проекта в Excluded Architectures > Any iOS (не путать с Any iOS Simulator) нужно добавить armv7 и x86_64 для их исключения.
