### ISSUE TITLE
версия 4.0.0-lite крашится на iphone 5S

### ISSUE THREAD

**Issue by ufsergey** [yandex/mapkit-ios-demo#112]
крашится на iphone 5S при вызове moveWithCameraPosition: , в Яндекс метрике есть лог:

Crashed: Thread
NSInternalInconsistencyException UnitSize is undefined if zoom is not finite or less than 0
0  CoreFoundation     __exceptionPreprocess + 216
1  libobjc.A.dylib    objc_exception_throw + 56
2  CoreFoundation     -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:] + 0
3  Foundation         -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 128
4  Myapp      _yandex_impl___ZN5boost4asio6detail31reactive_socket_connect_op_base10do_performEPNS1_10reactor_opE + 7339768

**Comment by ufsergey** [comment]
решено

**Comment by xzeror** [comment]
Как полечили?

**Comment by tegozen** [comment]
> Как полечили?

размер карты слишком маленький был. нужно перед рендером карты узнать размер страницы в которую она вписана и при инициализации - выставить размер сразу.
