### ISSUE TITLE
Как визуализировать линейку на карте?

### ISSUE THREAD

**Issue by dsenash** [yandex/mapkit-ios-demo#114]
Приветствую. Что-то не могу найти в доке. Как визуализировать линейку на карте?
Ну чтобы меняя масштаб понимать расстояния визуально. В целом как на Яндекс картах. Может быть в другом стиле.
Сначала сам думал считать и обрисовывать, но потом подумал что может быть строенная фичера. 
Но в доке не нашел. 
Спасибо

**Comment by eberkovich** [comment]
Здравствуйте, встроенной линейки - нет.

**Comment by dsenash** [comment]
Я подумал, что может быть неправильно выразил свой вопрос. Интересует так называемая ScaleLine. Масштабная линейка.

**Comment by dsenash** [comment]
![image](https://user-images.githubusercontent.com/9079796/112144887-b9c16700-8bea-11eb-9a85-7540463494d2.png)

**Comment by eberkovich** [comment]
да, я так и понял,  но этот контрол - часть приложения карты, в mapkit он не входит, и пока планов его добавлять - нет.

**Comment by dsenash** [comment]
Спасибо.
