### ISSUE TITLE
Как получить координаты произвольной точки карты?

### ISSUE THREAD

**Issue by dsenash** [yandex/mapkit-ios-demo#115]
Приветствую. По subj в Android есть класс GeoPoint и MapController.
А для IOS как это называется?
Т.е. как бы обратный метод к YMKPoint. Из точки получить координаты.
Спасибо.

**Comment by eberkovich** [comment]
Здравствуйте,

Если я правильно понял, то требуется по экранным координатам получить географические.
Для этого нужно воспользоваться методом [screenToWorld](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKMapWindow.html#-screenToWorldWithScreenPoint).

Для android точно так же, классов GeoPoint и MapController в mapkit нет.

**Comment by dsenash** [comment]
Название сильное. :) Спасибо большое
