### ISSUE TITLE
Не могу получить языковые локализации адресов из результатов поиска 

### ISSUE THREAD

**Issue by taxi-armenia-ios-team** [yandex/mapkit-ios-demo#116]
Я использую `searchSession: YMKSearchSession? = searchManager.submit(with: YMKPoint, zoom: NSNumber, searchOptions: YMKSearchOptions, responseHandler: YMKSearchSessionResponseHandler)`, чтобы получать YMKSearchResponse, который содержит адрес точки YMKPoint.
На данный момент адреса получаются только на английском. 
Хочу знать, как можно получать результаты на других языках тоже (на данный момент интересуют русский и армянский).

**Comment by elricbk** [comment]
Ответ определяется локалью запроса, поэтому за один запрос получить ответы на разных языках не получится. Локаль запроса определяется или автоматически (из настроек телефона/эмулятора) или через `MapKitFactory.setLocale()`.
