### ISSUE TITLE
Не работает построение маршрутов YandexMapKit 3.5.0

### ISSUE THREAD

**Issue by Vladimirmlnkv** [yandex/mapkit-ios-demo#118]
Несколько дней назад перестало работать построение маршрутов. Данный код работал в течении года, сейчас по какой-то причине не отрабатывает callback в методе requestRoutes у объекта YMKDrivingRouter. Даже не выдает ошибку. Пробовал создавать разные ключи - не помогло. 

`      let drivingRouter = YMKDirections.sharedInstance().createDrivingRouter();
        drivingSession = drivingRouter.requestRoutes(
            with: requestPoints,
            drivingOptions: YMKDrivingDrivingOptions()) {
                        (routesResponse: [YMKDrivingRoute]?, error: Error?) -> Void in
            if let routes = routesResponse {
                self.onRoutesReceived(routes)
            } else {
                self.onRoutesError(error!)
            }
        }
        `

**Comment by eaniconer** [comment]
> Пробовал создавать разные ключи - не помогло.

Обычно нужно подождать какое-то время после создания нового ключа, чтобы он активировался. Возможно уже все починилось, проверьте еще раз.

> сейчас по какой-то причине не отрабатывает callback

Проверил у себя: запустил демо-проект, выбрал пункт Driving, маршрут построился (callback отрабатывает)

<img width="372" alt="Screenshot 2021-05-26 at 11 04 14" src="https://user-images.githubusercontent.com/30935034/119624887-46b6b580-be12-11eb-87ab-beab137d7852.png">

**Comment by Vladimirmlnkv** [comment]
Помогла именно переустановка приложения. Удалил и запустил по новой - маршрут начал строиться.
С ожиданием активации ключа это никак не связано, перестало работать с ключом, который был создан несколько месяцев назад. После переустановки работает с тем же ключом.
Могу ли я еще какую-то информацию предоставить, чтобы можно было как-то это отладить?
