### ISSUE TITLE
Добавление всплывающего окна с информацией об объекте

### ISSUE THREAD

**Issue by alexandertopskiy** [yandex/mapkit-ios-demo#119]
Не кидайтесь камнями, плиз, я ещё совсем новичок в iOS-dev

Вопрос не совсем про работу с mapkit, скорее про uikit
Не знаю, как реализовать подобный функционал, чтобы при нажатии на объект появлялась вьюшка как в картах Яндекса (скрины прикрепляю) на половину экрана, которую можно развернуть на весь экран 
![image](https://user-images.githubusercontent.com/63578811/120045648-2c9af400-c019-11eb-8976-000e1b467a4e.png)
![image](https://user-images.githubusercontent.com/63578811/120045669-3ae91000-c019-11eb-9d9c-19efc8dfeb88.png)

Пробовал различные uiview, но не могу сделать подобного 
Сегвей на обычный viewcontroller сделал, информация передаётся,с этим все ок, но мне не совсем нравится такой вариант, хотелось бы так же, как в приложении Яндекс.карты

**Comment by eberkovich** [comment]
Прошу прощения, но вопрос совсем не про мапкит.

**Comment by alexandertopskiy** [comment]
да, не совсем туда вопрос задал, просто подумал, что здесь шанс найти ответ больше
если кто-то ищет ответ на подобный вопрос, то мне помог этот пример: https://github.com/martinnormark/HalfModalPresentationController
