### ISSUE TITLE
Локализация карты на русском языке

### ISSUE THREAD

**Issue by golovkinV** [yandex/mapkit-ios-demo#122]
Здравствуйте

Возможно ли отвязать отображение адреса на языке, установленном на девайсе, и указать явно, чтобы адрес возвращался на русском языке ?

Например, на телефоне установлен системный язык английский, и адрес возвращается в таком виде - ulitsa Lenina. Необходимо получать адрес всегда на русском.

**Comment by dmitriykotenko** [comment]
Надо добавить такую строчку в `AppDelegate.application(_, didFinishLaunchingWithOptions: _)`:

`YMKMapKit.setLocale("ru_RU")`

**Comment by SuleymanovKamil** [comment]
@YandexMapKit  можно ли поменять локализацию "на лету", без перезагрузки?
