### ISSUE TITLE
Пример использования YMKSearchSession (поиска координат по строке адреса)

### ISSUE THREAD

**Issue by kirill404** [yandex/mapkit-ios-demo#123]
Добрый день.
Можно привести польный пример использования YMKSearchSession, для поиска координат по строке адреса (geometry - неизвестна).

Спасибо.

Вот мой вариант:

let searchOpt = YMKSearchOptions()
        searchOpt.geometry = true
        searchOpt.searchTypes = .geo
        searchOpt.suggestWords = true
        
        let searchManager2 = YMKSearch.sharedInstance().createSearchManager(with: .combined)
        searchManager2.submit(withText: suggestItem.displayText ?? "",
                             geometry: YMKGeometry(boundingBox: YMKBoundingBox(southWest: YMKPoint(latitude: 55.514053, longitude: 6.979870), northEast: YMKPoint(latitude: 55.961338, longitude: 38.042797))),
                             searchOptions: searchOpt) { (res, err) in
            print("==suggestItem.displayText: \(suggestItem.displayText)")
            print("===res: \(res)")
            print("===err: \(err)")
        }
        
Но он не выполняется, почему?

**Comment by elricbk** [comment]
Пример использования есть [здесь][1]. Обратите внимание, что результат вызова `submit`, нужно сохранять, например, в поле класса.

По поводу геометрии – какую-то передать всё равно нужно. Можно взять местоположение пользователя. Можно просто передавать полигон всей страны или какого-то города, например. Геометрия влияет на разрешение неоднозначностей при поиске. Если искать только полные адреса вида «Россия, Саратов, проспект Кирова, 42», то от геометрии особо ничего не зависит. Если просто «проспект Кирова, 42», то без геометрии сложно понять, что именно хотел пользователь.

[1]: https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/SearchViewController.swift#L41

**Comment by elricbk** [comment]
И по поводу интеграции с саджестом – если уже есть `suggestItem`, то правильно будет проверить, есть ли в нём [URI][1]:
* если URI есть, то вместо `submit` нужно использовать [`resolveURI`][2]
* если URI нет, то вместо `suggestItem.displayText` для поиска нужно использовать `suggestItem.searchText`

[1]: https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKSuggestItem.html#uri
[2]: https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKSearchManager.html#-resolveURIWithUrisearchOptionsresponseHandler

**Comment by kirill404** [comment]
Подскажите в каких свойствах искать адрес при поиске по координатам?

Вот что я использую, но не могу найти свойство с текстовым адресом:

            let searchOpt = YMKSearchOptions()
            searchOpt.geometry = true
            searchOpt.searchTypes = .geo
            searchOpt.suggestWords = true
        
            let pointToSearch = YMKPoint(latitude: cameraPosition.target.latitude, longitude: cameraPosition.target.longitude)
            
            searchSession = searchManager.submit(with: pointToSearch, zoom: 12, searchOptions: searchOpt, responseHandler: { (res, err) in
                let first = res?.collection.children.first   ???  куда дальше чтобы получеть текст адреса?
                

Спасибо за вашу своевременную и неоценимую помощь.

**Comment by elricbk** [comment]
Предлагаю почитать [статью на Хабре][1]. Там как раз про всё это есть подробно с картинками и примерами кода (правда, на Kotlin).

[1]: https://habr.com/ru/company/yandex/blog/428564/
