### ISSUE TITLE
Check if region contains YMKPoint

### ISSUE THREAD

**Issue by AntonLunegovPerm** [yandex/mapkit-ios-demo#125]
Hello,

how I can check, if region(bounds of the screen) contains YMKPoint?

**Comment by eberkovich** [comment]
Hello, 

You can get visible region using [YMKMapWindow,focusRegion](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKMapWindow.html#focusRegion) and check if it contains point.
Mapkit does not have API to check does polygon contains point.

Please keep in mind focusRegion is not necessary rectangle it can be trapezoid if tilt != 0.
