### ISSUE TITLE
Получение координат точки при тапе на карту.

### ISSUE THREAD

**Issue by CBLR** [yandex/mapkit-ios-demo#128]
Подскажите пожалуйста, как при тапе на карту можно получить координаты точки, для дальнейшего геокодирования, на которую нажали?
Использую `func onObjectTap(with: YMKGeoObjectTapEvent) -> Bool`, но вытащить координаты не получилось(

Заранее спасибо!

**Comment by kebrick** [comment]
Если через YMKGeoObjectTapEvent то:

`event.geoObject.geometry.first?.point`
