### ISSUE TITLE
Не работают все типы mapType, кроме .map

### ISSUE THREAD

**Issue by ShagaleevAlexey** [yandex/mapkit-ios-demo#13]
Если установить `mapView?.mapWindow.map?.mapType = .satellite`, то вместо карты во вью будет подложка из квадратов. Зум при этом будет работать. Эта же проблема проявляется при выборе `.hybrid` и `.vectorMap`.

**Comment by vbazhenov** [comment]
Это ожидаемое поведение – к сожалению, мы не можем отдавать тайлы спутниковых и гибридных карт внешним пользователям.

**Comment by ShagaleevAlexey** [comment]
А где нибудь про это сказано? В коммерческой версии нет такого, в условиях использования тоже не сказано, что такие действия ограничиваются. Хотелось бы иметь больше понимания в этом плане.

**Comment by ShagaleevAlexey** [comment]
> Это ожидаемое поведение – к сожалению, мы не можем отдавать тайлы спутниковых и гибридных карт внешним пользователям.

Разве ожидаемо? Несколько раз перечитал доку, нигде об этом не написано. Хотелось бы больше понимания в этом плане.
