### ISSUE TITLE
Unrecognized selector sent to class

### ISSUE THREAD

**Issue by mipopov** [yandex/mapkit-ios-demo#130]
всем привет! Внедряю Яндекс карты в проект и при установке ключа, бросает ошибку

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[YMKMapKit setApiKey:]: unrecognized selector sent to class 0x1025498e8'
_LSContextInitReturningError() failed with error Error Domain=NSOSStatusErrorDomain Code=-10817 "(null)" UserInfo={_LSFunction=_LSSchemaConfigureForStore, ExpectedSimulatorHash={length = 32, bytes = 0x15dde658 ed2a1267 ab2496d7 34f186ad ... ec431c65 02d68f35 }, _LSLine=409, WrongSimulatorHash={length = 32, bytes = 0xaf25dda9 e45baa35 610eaabd 5bc09901 ... 9cbe61f3 81d7b9d9 }}
terminating with uncaught exception of type NSException
CoreSimulator 757.5 - Device: iPad Pro (9.7-inch) (41AAFAE6-F1F5-4153-AC4B-1C8D7CE6BE33) - Runtime: iOS 14.5 (18E182) - DeviceType: iPad Pro (9.7-inch)

**Использую Mac c M1**
Кто-нибудь сталкивался с такой проблемой? есть решение?

**Comment by YaphetS1** [comment]
Нашел в чем проблема. Добавь в linker setting -objc.
Если же делаешь через SPM то придется добавлять это через .unsafeFlags(["-ObjC"])

**Comment by andrey-svx** [comment]
@YaphetS1, тоже словил этот баг. Подскажи пожалуйста где именно в настройках пакета указать .unsafeFlags(["-ObjC"])?

**Comment by andrey-svx** [comment]
Разобрался. При работе со SwiftPM в декларации пакета необходимо указать 
import PackageDescription

let package = Package(
    name: "PackageName",
    platforms: [
        .iOS(.v13)
    ],
    products: [
        .library(
            name: "PackageName",
            targets: [
                "PackageName"
            ]),
    ],
    dependencies: [
        .package(url: "https://site-where-yandex-maps-mobile-xcframework-is", from: "4.1.0")
    ],
    targets: [
        .target(
            name: "PackageName",
            dependencies: [
                .product(name: "YandexMapsMobile", package: "YandexMapsMobilePackageName")
            ],
            **linkerSettings: [
                .unsafeFlags(["-ObjC"])
            ]**
        )
    ]
)
