### ISSUE TITLE
Крэши

### ISSUE THREAD

**Issue by maxprig** [yandex/mapkit-ios-demo#131]
Добрый день! Ловим Крэши карты в аналитике, подскажите, пожалуйста, роняет ли это приложение и можно ли как-то пофиксить?

`
Cras

- hed: Network
- 0  libsystem_kernel.dylib         0x1c0b14598 write + 8
- 1  app                            0x105656abc sock_write + 426496
- 2  app                            0x1056549c8 _yandex_impl__BIO_write + 418060
- 3  app                            0x10561daa0 _yandex_impl__ssl3_write_pending + 192996
- 4  app                            0x10561dbb4 _yandex_impl__do_ssl3_write + 193272
- 5  app                            0x105624190 _yandex_impl__ssl3_dispatch_alert + 219348
- 6  app                            0x105623788 _yandex_impl__ssl3_shutdown + 216780
- 7  app                            0x105819320 Curl_ossl_close + 2271844
- 8  app                            0x1057e89f4 _yandex_impl__Curl_disconnect + 2072888
- 9  app                            0x1057eafc8 create_conn + 2082572
- 10 app                            0x1057e95d0 _yandex_impl__Curl_connect + 2075924
- 11 app                            0x1057f8c84 multi_runsingle + 2139080
- 12 app                            0x1057fa0e4 multi_socket + 2144296
- 13 app                            0x1057fa1c4 _yandex_impl__curl_multi_socket_action + 2144520
- 14 app                            0x10550e20c std::__1::__function::__func<yandex::maps::runtime::network::http::curl::MultiHandle::startTimeout(void*, long, yandex::maps::runtime::network::http::curl::MultiHandle*)::$_7, std::__1::allocator<yandex::maps::runtime::network::http::curl::MultiHandle::startTimeout(void*, long, yandex::maps::runtime::network::http::curl::MultiHandle*)::$_7>, void ()>::operator()() + 10600
- 15 app                            0x1054caff0 boost::asio::detail::wait_handler<yandex::maps::runtime::network::common::Timer::startTimeout(long, std::__1::function<void ()>)::$_0>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) + 2032
- 16 app                            0x1054daf80 _yandex_impl___ZN5boost4asio6detail9scheduler10do_run_oneERNS1_27conditionally_enabled_mutex11scoped_lockERNS1_21scheduler_thread_infoERKNS_6system10error_codeE + 67456
- 17 app                            0x1054dab8c _yandex_impl___ZN5boost4asio6detail9scheduler3runERNS_6system10error_codeE + 66444
- 18 app                            0x1054d8e04 yandex::maps::runtime::network::common::NetworkManagerImpl::run() + 58884
- 19 app                            0x1054dcd8c void yandex::maps::runtime::internal::threadRunner<yandex::maps::runtime::network::common::NetworkManagerImpl::NetworkManagerImpl(yandex::maps::runtime::network::common::NetworkConfig const&)::$_0>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, yandex::maps::runtime::ThreadPriority, yandex::maps::runtime::network::common::NetworkManagerImpl::NetworkManagerImpl(yandex::maps::runtime::network::common::NetworkConfig const&)::$_0&&) + 75148
- 20 app                            0x1054dcdd8 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, yandex::maps::runtime::ThreadPriority, yandex::maps::runtime::network::common::NetworkManagerImpl::NetworkManagerImpl(yandex::maps::runtime::network::common::NetworkConfig const&)::$_0&&), std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, yandex::maps::runtime::ThreadPriority, yandex::maps::runtime::network::common::NetworkManagerImpl::NetworkManagerImpl(yandex::maps::runtime::network::common::NetworkConfig const&)::$_0> >(void*) + 75224
- 21 libsystem_pthread.dylib        0x1de594bfc _pthread_start + 320
- 22 libsystem_pthread.dylib       

 0x1de59d758 thread_start + 8
`

Версия мапкита и рантайма - 3.5.0

**Comment by mkdk** [comment]
+1

**Comment by CBBBrother** [comment]
> 

На 4.1.0 не пробовали обновиться?

**Comment by maxprig** [comment]
Спасибо за оперативный ответ, но я уже уволился оттуда :D
