### ISSUE TITLE
Запуск тестов на simulator c ios 15

### ISSUE THREAD

**Issue by Dezabro** [yandex/mapkit-ios-demo#133]
Привет. 

Возникла проблема с запуском тестов из development pods, содержащих dependency на YandexMapsMobile', '4.0.0-full'.  Тесты просто не запускаются, висит бесконечно Testing, потом падает с выдачей spindump. 

<img width="815" alt="Screenshot 2021-11-01 at 11 53 31" src="https://user-images.githubusercontent.com/15033711/139646726-5c7142a6-8785-435d-b84d-02888aecde78.png">

Если убрать dependency или запустить на simulator ios 14 - то все ок. 

Кажется, проблема точно такая же, как описана у Texture: https://github.com/TextureGroup/Texture/issues/2029 и на форуме apple - https://developer.apple.com/forums/thread/689592?answerId=688696022#688696022

Демо проект (добавил в ваш демо проект dev pod с dependecy на  YandexMapsMobile)
[mapkit-ios-demo_deadlock_.zip](https://github.com/yandex/mapkit-ios-demo/files/7451931/mapkit-ios-demo_deadlock_.zip)
(запуск TestFeatureTests на ios 15 симулятор)

Spindump: 
[Bootstrap Hang_0_B6235CD3-8596-4D65-A094-F80F3168A10C.spindump.zip](https://github.com/yandex/mapkit-ios-demo/files/7451892/Bootstrap.Hang_0_B6235CD3-8596-4D65-A094-F80F3168A10C.spindump.zip)

Пробовал xcode 13 и xcode 13.1 - результат одинаковый

**Comment by artyom-razinov** [comment]
Выпилил YandexMapKit, тесты заработали.

**Comment by artyom-razinov** [comment]
@Dezabro это похоже на баг в iOS 15, создали задачку эпплам, будем ждать фикса.

Любой вызов к UIKit в +(void)load в произвольном фреймворке приводит к дедлоку.

Ясное дело, конечно, что load и initialize - это антипаттерн и стыдобища (если это не для обхода багов эппла, конечно), но этот дедлок всё-таки больше баг эппла.

**Comment by artyom-razinov** [comment]
Костыль - в настройках схемы добавить `DYLD_INSERT_LIBRARIES`.

В нём прописать путь до бинаря фреймворка, в котором происходит вызов в +(void)load к другому фреймворку (например, к UIKit).

В нашем случае (мы мержим яндекс карты и прочие фреймворки в единый фреймворк для оптимизации быстродействия):
 
`$(BUILT_PRODUCTS_DIR)/AvitoForTests.app/Frameworks/AvitoFoundation.framework/AvitoFoundation`

Это решает проблему дедлока и тесты на iOS 15 запускаются.

**Comment by beefon** [comment]
Эпл ответили что теперь так и будет. Думаю, @yandex должен пофиксить.

**Comment by navartis** [comment]
Мы пофиксили у себя зависание тестов.

В нашем случае в приложении `TheApp` есть локальная зависимость `InternalProjectDependency`, которая зависит от `YandexMaps`

Мы прописали в настройки билдсхемы тестов Environment Variable `DYLD_INSERT_LIBRARIES` значение 
`$(BUILT_PRODUCTS_DIR)/TheApp.app/Frameworks/InternalProjectDependency.framework/InternalProjectDependency`

И тесты перестали зависать на 15x симуляторах.

Если у вас более сложная ситуация с зависимостями, то `DYLD_INSERT_LIBRARIES` поддерживает список.
`man dyld` в помощь - там много полезных переменных для отладки компиляции проекта.

А можно просто перевести тесты на TestPlans и хак с зависанием тестов вам не потребуется;)

@artyom-razinov Спасибо за наводку!
