### ISSUE TITLE
- [YMKSearchManager submitWithPoint:zoom:searchOptions:responseHandler:]   without any callback.

### ISSUE THREAD

**Issue by ytmoye** [yandex/mapkit-ios-demo#134]
Hi, developer of yandex mapkit.

I want to use geocoding feature of Yandex MapKit. But when i use the  "- [YMKSearchManager submitWithPoint:zoom:searchOptions:responseHandler:]" API, there is no any callback. I don't know what went wrong. And i use the free version mapkit, do I need a licensed version to use the geocoding feature? I took a look at the documentation,  and did not find the exact statement.

Here is my code:
```
if (!self.searchManager) {
    self.searchManager = [[YMKSearch sharedInstance] createSearchManagerWithSearchManagerType:YMKSearchSearchManagerTypeCombined];
}
YMKPoint *p = [YMKPoint pointWithLatitude:point.latitude longitude:point.longitude];
YMKSearchOptions *op = [YMKSearchOptions new];
op.searchTypes = YMKSearchTypeGeo;
 [self.searchManager submitWithPoint:p zoom:@14 searchOptions:op responseHandler:^(YMKSearchResponse * _Nullable response, NSError * _Nullable error) {
    NSLog(@"%@", response);
}];
```

Please help answer my question,  thank you very much.

**Comment by elricbk** [comment]
Hi! All `submit*` methods return the session to be saved in the class field. If the session is not saved, it will be immediately destroyed and the request will be canceled.

**Comment by ytmoye** [comment]
@elricbk  it's working now，thank you very much.
