### ISSUE TITLE
Добавление label на YMKPolygonMapObject

### ISSUE THREAD

**Issue by bondsy777** [yandex/mapkit-ios-demo#135]
Как добавить метку описания на полигон ios sdk?

<img width="521" alt="Screenshot 2021-11-26 at 12 46 00" src="https://user-images.githubusercontent.com/55878329/143552980-ff8b32eb-ff3b-4820-ac17-db002aca6193.png">

**Comment by eberkovich** [comment]
Мапкит не умеет подписывать полигоны, но подпись или любую UIView можно привязать к точечному  YMKPlacemarkMapObject. Вот [пример](https://github.com/yandex/mapkit-ios-demo/blob/29921964666bc5ab6fd76f40f6c2a9dabaa28ba3/MapKitDemo/MapObjectsViewController.swift#L189).

**Comment by bondsy777** [comment]
Спасибо что ответили, уже разобрался, как раз по примеру из MapKitDemo.
