### ISSUE TITLE
Поддержка vector layer.

### ISSUE THREAD

**Issue by valentina-zueva** [yandex/mapkit-ios-demo#137]
По-видимому, в текущем сдк (4.0.0) есть методы поддержки вектора для тайлов:
`- (nonnull YMKLayer *)addLayerWithLayerId:(nonnull NSString *)layerId
                              contentType:(nonnull NSString *)contentType
                             layerOptions:(nonnull YMKLayerOptions *)layerOptions
                          tileUrlProvider:(nonnull id<YMKTilesUrlProvider>)tileUrlProvider
                         imageUrlProvider:(nonnull id<YMKResourceUrlProvider>)imageUrlProvider
                         modelUrlProvider:(nonnull id<YMKResourceUrlProvider>)modelUrlProvider
                         glyphUrlProvider:(nonnull id<YMKGlyphsGlyphUrlProvider>)glyphUrlProvider
                               projection:(nonnull YMKProjection *)projection
                               zoomRanges:(nonnull NSArray<YMKZoomRange *> *)zoomRanges`
                               
Какие форматы поддерживаются? svg? Можно ли где-то подробнее узнать как это работает, документация или пример?

**Comment by eberkovich** [comment]
Поддерживаются тайлы в формате geojson, к сожалению документация по этой функциональности в данный момент отсутствует, но есть [пример](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/GeoJsonViewController.swift).
