### ISSUE TITLE
Не работает YMKUserLocationView.arrow.isVisible

### ISSUE THREAD

**Issue by DCrow** [yandex/mapkit-ios-demo#139]
Добрый день

В примере если в `UserLocationViewController` изменить строчку
`view.arrow.setIconWith(UIImage(named:"UserArrow")!)` на `view.arrow.isVisible = false`, иконка при движении все равно отображается.

Ожидалось что в таком случае она не будет отображаться.

**Comment by YandexMapKit** [comment]
Для изменения видимости нужно использовать [setVisible](https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/user_location/UserLocationLayer.html#_4).

**Comment by DCrow** [comment]
Приведенный вами метод существует только на андроид, для iOS такого метода нет.
