### ISSUE TITLE
Как отключить anchor mode?

### ISSUE THREAD

**Issue by dsenash** [yandex/mapkit-ios-demo#14]
Использую режим движения с автоцентрированием карты через anchor.
Однако хотел бы иметь возможность в отсутствии движения отключать данный режим.
Но обнаружил что свойство isAnchorEnabled - read-only. 
Как правильно отключать автоцентрирование?
Спасибо

**Comment by dimi3o** [comment]
Занимаюсь решением того же вопроса. Для UserLocationLayer есть метод resetanchor(), но его использование не приводит к отключению автоцентирования. Похоже надо как-то по-другому. Например, при создании слоя UserLocationLayer указать правильные опции. Документация очень скудная.
