### ISSUE TITLE
Thread explosion

### ISSUE THREAD

**Issue by nitrey** [yandex/mapkit-ios-demo#142]
Обнаружили, что при использовании YMK создаётся излишне большое число потоков, что негативно сказывается на производительности приложения. Проверили на своей стороне — всё инициализируется как надо

![thread_explosion](https://user-images.githubusercontent.com/17312879/168759076-5122cb00-f49d-4c59-9dc8-3ea47627bdcf.png)

**Comment by YandexMapKit** [comment]
Спасибо за информацию. Задачу взяли в работу, но каких-либо сроков исправления ситуации сообщить не можем.
