### ISSUE TITLE
Как использовать функции Yandex Map если приложение написано на swiftui

### ISSUE THREAD

**Issue by IHIierO** [yandex/mapkit-ios-demo#149]
Подскажите пожалуйста, я не совсем понимаю как использовать функции такие как поиск, построение маршрута и т.д. если мое приложение написано на SwiftUI?

**Comment by platon-p** [comment]
#129

**Comment by aramayyes** [comment]
Можно использовать эту библиотеку: [YandexMapsSwiftUI](https://github.com/aramayyes/YandexMapsSwiftUI)
