### ISSUE TITLE
Could not cast value of type 'YMKPlacemarkMapObject' (0x11686f1d8) to 'YMKPlacemarkMapObject' (0x11d783958).

### ISSUE THREAD

**Issue by max270598** [yandex/mapkit-ios-demo#150]
i have cluster collection and for placeMarks in  this collection i added YMKMapObjectTapListener.

<img width="747" alt="Screenshot 2022-07-14 at 10 54 01" src="https://user-images.githubusercontent.com/32710518/178931238-37cd35d5-6612-475d-9091-b24dbba4fa95.png">

this is my onMapObjectTap method

<img width="651" alt="Screenshot 2022-07-14 at 10 56 36" src="https://user-images.githubusercontent.com/32710518/178931719-aeb0e72d-4ba9-4ac7-906c-bf18018826eb.png">

and when i click on a placemark, i got crash with this error
"Could not cast value of type 'YMKPlacemarkMapObject' (0x111c031d8) to 'YMKPlacemarkMapObject' (0x118b17960)."

<img width="1031" alt="Screenshot 2022-07-14 at 10 58 56" src="https://user-images.githubusercontent.com/32710518/178932218-897257f6-71e7-49a6-b429-f372571faf10.png">

What am i doing wrong?

**Comment by xzeror** [comment]
Because you are using clusterized collection you should implement two tap listeners: one for object taps (the one you have implemented), and the other one for cluster taps, e.g.:
```
func onClusterTap(with cluster: YMKCluster) -> Bool {
        // do smth with cluster here (zoom in for example)
        return true
    }

    func onMapObjectTap(with mapObject: YMKMapObject, point _: YMKPoint) -> Bool {
        guard let placemarkObj = mapObject as? YMKPlacemarkMapObject else { return false } 
        // do smth with object here 
        return true
    }
```
