### ISSUE TITLE
Ошибка компиляции при запуске тест билда в xcode

### ISSUE THREAD

**Issue by iamakhin** [yandex/mapkit-ios-demo#153]
Добавляю карты в голый проект.
Добавляю тесты.

Пытаюсь запутстить тест билд на m1 под розеттой и компилятор выдает ошибку:

Undefined symbols for architecture x86_64:
  "__yandex_impl__OPENSSL_ia32cap_P", referenced from:
      __yandex_impl__OPENSSL_cpuid_setup in YandexMapsMobile(cryptlib.c.o)
      __yandex_impl__EVP_aes_128_cbc in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_ecb in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_ofb in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_cfb128 in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_cfb1 in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_cfb8 in YandexMapsMobile(e_aes.c.o)
      ...
ld: symbol(s) not found for architecture x86_64

<img width="1704" alt="Screen Shot 2022-07-20 at 11 35 48" src="https://user-images.githubusercontent.com/93322693/179936881-0db6306f-5012-4adb-b690-ef76f5465242.png">

**Comment by vladislav-m** [comment]
У меня идентичная проблема. На m1 собираются тесты нормально, а на intel/rosetta вот такую ошибку выдает.

**Comment by vladislav-m** [comment]
Мы решили эту проблему путем исключения пода я.карт из тестовых таргетов

**Comment by iamakhin** [comment]
Мы тоже пошли таким же путем, но хотелось бы чтобы все таки была возможность работы с тест таргетом
