### ISSUE TITLE
Как работает focusRect?

### ISSUE THREAD

**Issue by user1231232131** [yandex/mapkit-ios-demo#155]
Можно ли менять значение focusRect/focusPoint во время работы карты? На экране предусмотрено 2 состояния: карта в полный экран и карта, перекрытая боттомШит снизу до половины. Состояния эти меняются.  При попытке изменить значения focusRect/focusPoint карта дергается в область близкую к необходимой, а затем метод move подъезжает до необходимой точки с анимацией. Происходят эти дерганья рандомно, поэтому решил узнать можно ли вообще менять значения этих параметров когда карта уже находится на экране, или только при запуске один раз. В решении использовал рекомендации из https://github.com/yandex/mapkit-ios-demo/issues/127, https://github.com/yandex/mapkit-android-demo/issues/117.
В целом проблем в работе focusRect после установки нет, методы move центрирую камеру в нужной области, поэтому думаю, что все остально сделано верно.

**Comment by teshca** [comment]
Указанные методы можно вызывать в любое время

**Comment by user1231232131** [comment]
Спасибо за оперативный ответ. Накидал пример который показывает какое поведение я имею в виду. Или в примере можно исправить что-то?

`class MapViewController: UIViewController {
    @IBOutlet private weak var mapView: YMKMapView!
    
    private let TARGET_LOCATION = YMKPoint(latitude: 59.945933, longitude: 30.320045)
    private var MAP_SIZE = CGSize.zero
    
    override func viewDidLoad() {
        super.viewDidLoad()
        mapView.mapWindow.addSizeChangedListener(with: self)
        setupGestures()
        setupPlacemark()
        moveMap()
    }
    
    @objc func centerTapped() {
        mapView.mapWindow.focusRect = .init(topLeft: .init(x: 0,
                                                           y: 0),
                                            bottomRight: .init(x: Float(MAP_SIZE.width),
                                                               y: Float(MAP_SIZE.height)))
        moveMap()
    }
    
    @objc func topTapped() {
        mapView.mapWindow.focusRect = .init(topLeft: .init(x: 0,
                                                           y: 0),
                                            bottomRight: .init(x: Float(MAP_SIZE.width),
                                                               y: Float(MAP_SIZE.height) / 2))
        moveMap()
    }
    
    private func setupPlacemark() {
        _ = mapView.mapWindow.map.mapObjects.addCircle(with: .init(center: TARGET_LOCATION,
                                                                   radius: 20),
                                                       stroke: .red,
                                                       strokeWidth: 2,
                                                       fill: .blue)
    }
    
    private func setupGestures() {
        let tapGesture = UITapGestureRecognizer(target: self, action: #selector(topTapped))
        let doubleTapGesture = UITapGestureRecognizer(target: self, action: #selector(centerTapped))
        doubleTapGesture.numberOfTapsRequired = 2
        tapGesture.require(toFail: doubleTapGesture)
        mapView.addGestureRecognizer(tapGesture)
        mapView.addGestureRecognizer(doubleTapGesture)
    }
     
    private func moveMap() {
        mapView.mapWindow.map.move(
            with: YMKCameraPosition(target: TARGET_LOCATION, zoom: 15, azimuth: 0, tilt: 0),
            animationType: YMKAnimation(type: YMKAnimationType.smooth, duration: 5),
            cameraCallback: nil)
    }
}

extension MapViewController: YMKMapSizeChangedListener {
    func onMapWindowSizeChanged(with mapWindow: YMKMapWindow, newWidth: Int, newHeight: Int) {
        MAP_SIZE = .init(width: newWidth,
                         height: newHeight)
    }
}
`

**Comment by teshca** [comment]
Не совсем понятно какого эффекта вы пытаетесь добиться вызывая mapMove после установки focusRect
Изменение focusRect  само по себе приведет к смещению карты в состояния где TARGET_LOCATION будет находиться в его центре.

**Comment by user1231232131** [comment]
Наверно я неправильно понял суть работы focusRect. А как можно добиться, чтобы смещение при установке focusRect происходило плавно, а не просто перебрасывало?

**Comment by teshca** [comment]
Одновременно с выставлением focusRect нужно позвать move без анимации который вернет камеру на старое место, после этого запустить move с анимацией.

**Comment by user1231232131** [comment]
Условно если камера до момента изменения focusRect была направлена в центр экрана, то шаги следующие:
- установить focusRect нужный
- рассчитать предыдущий центр относительно нового (focusRect центр), ибо камера уже центрируется иначе
- направить камеру без анимации на него
- вызвать move в нужную мне точку
А есть ли готовый способ рассчитать положение центра на шаге 2? Просто сейчас вижу путь только конвертировать физические координаты экрана в гео, может есть что-то правильное

**Comment by teshca** [comment]
без конвертации не обойтись

`
YMKPoint *target = [self.mapView.mapWindow screenToWorldWithScreenPoint:focusPoint];
YMKCameraPosition *position = self.map.cameraPosition;
 
self.mapView.mapWindow.focusPoint = focusPoint;
 
YMKCameraPosition *newPosition = [YMKCameraPosition cameraPositionWithTarget:target zoom:position.zoom azimuth:position.azimuth tilt:position.tilt];
[self.map moveWithCameraPosition:newPosition];
`

**Comment by user1231232131** [comment]
Спасибо большое!
