### ISSUE TITLE
Не отображаются части карты при зуме или прокрутке  в 4.1.0-lite

### ISSUE THREAD

**Issue by ufsergey** [yandex/mapkit-ios-demo#157]
исчезает отрисовка дорог и домов , происходит рандомно на разном значении зума в разных местах карты, пример на скриншоте, выделено красным. На версии 3.5 все работает нормально

![Screen Shot 2022-08-10 at 11 14 35](https://user-images.githubusercontent.com/9317142/183840488-9c20cba4-9512-484a-8b1b-968ebe91d59b.png)

если использовать initWithFrame: vulkanPreferred:YES , то вроде бы это помогает, но добавляет тормоза. проверял на реальном iphone 6S plus

**Comment by antonkiselev** [comment]
Начиная с версии 4.1.0 (и в 4.2.0, 4.2.1) иногда у пользователей вообще не загружаются тайлы. Примерно в 70% это фиксится повторным заходом на карту или переоткрытием приложения, но иногда вообще никакие манипуляции не помогают.
Видео:
https://user-images.githubusercontent.com/7533101/201351263-00c04807-7355-4038-9b8c-42341522bbd6.mov

**Comment by xzeror** [comment]
Была такая же проблема с белыми картами. С некоторых пор, непонятно с каких, требуется инициализировать sharedInstance рядом с setApiKey, например так:

// В AppDelegate
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
    YMKMapKit.setApiKey(Constants.mapKey)
    YMKMapKit.sharedInstance()

    return true
}
В общем-то это описано в [документации](https://yandex.com/dev/maps/mapkit/doc/ios-quickstart/concepts/ios/quickstart.html), но к сожалению не в [change log](https://yandex.com/dev/maps/mapkit/doc/dg/concepts/versions.html) 🤷‍♂️
