### ISSUE TITLE
Огромное количество дебажных сообщений в консоли Xcode

### ISSUE THREAD

**Issue by iamakhin** [yandex/mapkit-ios-demo#158]
Очень сильно засоряется консоль в Xcode если просто открыть карты, а если открыть панорамы то вообще происходит какой-то ужас.
Ребята, было очень круто это как-то пофиксить)

<img width="1005" alt="Screen Shot 2022-08-10 at 12 51 58" src="https://user-images.githubusercontent.com/93322693/183872576-555b4304-7280-46b2-b2cb-0efac1d0d83f.png">

**Comment by eberkovich** [comment]
Чтобы уменьшить количество сообщений в логе можно поднять уровень логирования, для этого в файле *.plist нужно прописать yandex.maps.runtime.logging.Level=Error
