### ISSUE TITLE
 YMKPlacemarkMapObject direction не работает , 4.1.0-lite

### ISSUE THREAD

**Issue by ufsergey** [yandex/mapkit-ios-demo#159]
YMKPlacemarkMapObject.direction не работает , угол не меняется

**Comment by eberkovich** [comment]
Для того, чтобы иконка поворачивалась, нужно настроить IconStyle:

```
YMKIconStyle* rotatingIconStyle = [[YMKIconStyle alloc] init];
rotatingIconStyle.rotationType = [NSNumber numberWithInt:YMKRotationTypeRotate];
```
и дальше передать в addPlacemark либо позвать setIconStyle.

Смысл в том, что placemark может содержать несколько иконок (для этого нужно использовать CompositeIcon) и часть иконок могут вращаться вместе с placemark, а часть нет.
