### ISSUE TITLE
Краткое инфо по объекту на карте

### ISSUE THREAD

**Issue by SeminDmitriy** [yandex/mapkit-ios-demo#16]
Приветствую!
Правильно ли понимаю, что сценарий когда нажимаешь на `placemark` и появляется окно с краткой информацией, не реализуется стандартными средствами `SDK`? 
В этом случае необходимо добавлять новый `placemark` через метод` addPlacemark(with: view:)`, где в параметре `view` надо передавать ранее созданный элемент `UI` для отображения этой информации?

**Comment by eberkovich** [comment]
Здравствуйте,

Да, установить в placemark одновременно иконку и view нельзя.

**Comment by eberkovich** [comment]
Обычным системными средствами:
```
[uiView setOpaque:NO];
[uiView setBackgroundColor:[[UIColor clearColor] colorWithAlphaComponent:0.0]];
```

**Comment by aposnov** [comment]
тогда получается черный экран, а нужно именно прозрачность  https://yadi.sk/i/AMgxOYQH2pusFQ

**Comment by eberkovich** [comment]
А точно выставлен setOpaque:NO? проверил прямо сейчас - работает.
Возможно мешают какие-то другие настройки UIView, но это скорее вопрос по UIKit, а не по Mapkit.

**Comment by aposnov** [comment]
да сработало, спасибо большое.
для Swift это isOpaque = false, может кто то будет смотреть в будущем, чтобы пригодилось :)

**Comment by alexandertopskiy** [comment]
@aposnov , у вас случайно не остался этот проект? Хочу добавить в карты информацию по объекту на карте (чтобы как в Яндекс.Картах при тапе на объект снизу появлялась информация), но не могу понять, к чему прикрутить сегвей
