### ISSUE TITLE
Ошибка компиляции preview layout в swiftUI файлах при наличии YMK. Девайс/симулятор нормально.

### ISSUE THREAD

**Issue by boogiedimik** [yandex/mapkit-ios-demo#165]
При создании/редактировании любого вью на swiftUI происходит ошибка компиляции:

```
linker command failed with exit code 1 (use -v to see invocation)

----------------------------------------

LinkDylibError: Failed to build View.swift

Linking failed: linker command failed with exit code 1 (use -v to see invocation)

ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/SharedFrameworks-iphonesimulator'
ld: warning: directory not found for option '-F/Users/########/######/someFramework'
ld: warning: Could not find or use auto-linked framework 'FBLPromises'
Undefined symbols for architecture x86_64:
  "__yandex_impl__OPENSSL_ia32cap_P", referenced from:
      __yandex_impl__OPENSSL_cpuid_setup in YandexMapsMobile(cryptlib.c.o)
      __yandex_impl__EVP_aes_128_cbc in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_ecb in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_ofb in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_cfb128 in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_cfb1 in YandexMapsMobile(e_aes.c.o)
      __yandex_impl__EVP_aes_128_cfb8 in YandexMapsMobile(e_aes.c.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by kamiraider** [comment]
никакой инфы нет?

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный собранный пример, демонстрирующий описанную ситуацию. Вы можете выложить его проектом на **[GitHub](https://github.com/)** или загрузить на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку. Мы постараемся помочь.

**Comment by FuzzzzyBoy** [comment]
@YandexMapKit - https://gist.github.com/FuzzzzyBoy/1bcc3980819d397d900ed52a2d452074 - вот пример с крешом превью

**Comment by YandexMapKit** [comment]
Уточните детали, пожалуйста. Какая версия MapKit использовалась?

**Comment by kamiraider** [comment]
пробовал 4.2.1, 4.2.2 лайт и фулл

**Comment by FuzzzzyBoy** [comment]
> Уточните детали, пожалуйста. Какая версия MapKit использовалась?

Пробовал версию 4.3.1 Лайт через cocoa pods и как отдельный фреймворк

**Comment by YandexMapKit** [comment]
Пришлите, пожалуйста, минимальный пример проекта с которым возникают сложности? [Демо приложение](https://github.com/yandex/mapkit-ios-demo) успешно собирается под x86_64.

**Comment by FuzzzzyBoy** [comment]
> Пришлите, пожалуйста, минимальный пример проекта с которым возникают сложности? [Демо приложение](https://github.com/yandex/mapkit-ios-demo) успешно собирается под x86_64.

[YandexMapSample.zip](https://github.com/yandex/mapkit-ios-demo/files/11341198/YandexMapSample.zip)

Проблемы при билде swiftUI preview на M1 Pro

**Comment by FuzzzzyBoy** [comment]
@YandexMapKit какие нибудь апдейты по этой проблеме?

**Comment by YandexMapKit** [comment]
Апдейтов пока нет, ещё изучаем. Как только появятся новости, мы напишем.

**Comment by YandexMapKit** [comment]
Данная ситуация будет исправлена с выходом нового релиза 4.3.2. Ориентировочно, это должно произойти в течение одной-двух недель.

**Comment by FuzzzzyBoy** [comment]
@YandexMapKit а почему закрыли? Проблема же не решилась

**Comment by tikhomirov-dev** [comment]
Видимо, уже трёх-четырёх. И правда "completed"... 😋
