### ISSUE TITLE
OpenGLES is deprecated. Consider migrating to Metal instead.

### ISSUE THREAD

**Issue by yurapriv** [yandex/mapkit-ios-demo#172]
[YandexMapsMobile](https://github.com/CocoaPods/Specs/tree/master/Specs/d/d/0/YandexMapsMobile) требует подключения Фреймворка `OpenGLES` согласно `podspec`:
https://github.com/CocoaPods/Specs/blob/9f7860d47a5f08b5fe8d02aff20ff650401fec09/Specs/d/d/0/YandexMapsMobile/4.2.1-full/YandexMapsMobile.podspec.json#L24

`OpenGL ES` помечен как `Deprecated` начиная с `iOS 12` согласно документации:
https://developer.apple.com/documentation/opengles/

Соответственно, при сборке приложения с зависимостью `YandexMapsMobile` появляется предупреждение компилятора:
<img width="432" alt="Снимок экрана 2022-10-13 в 11 40 23" src="https://user-images.githubusercontent.com/7814127/195523504-98460ea9-2c59-4a07-a2e0-a27f37a8f83a.png">

Подскажите пожалуйста, планируется ли переход на `Metal` вместо `OpenGLES` для `YandexMapsMobile`?
Если планируется, то к какой дате?

Заранее благодарю за ответ, это очень важно для принятия решения об интеграции `YandexMapsMobile` в наш проект!

**Comment by eberkovich** [comment]
Планируется, работаем над этим.

**Comment by mishurov** [comment]
@eberkovich сделали бы как Qt Rendering Hardware Interface, там один код транслируется и на DirectX, и Metal, и OpenGL. Шейдеры SPIR-V и glslang.
