### ISSUE TITLE
Geo_json style layers

### ISSUE THREAD

**Issue by LuckyCoders** [yandex/mapkit-ios-demo#173]
Where can I found description of that properties?
[geo_json_style_example.json](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/Resources/geo_json_style_example.json)

After replace icon-image i got:
![IMG_A64ADA9AB865-1](https://user-images.githubusercontent.com/13001109/196080364-c2c0def5-90d7-4175-9e11-743cefa57f3e.jpeg)

**Comment by LuckyCoders** [comment]
please share even drafts if you have any of them

**Comment by YandexMapKit** [comment]
We have decided to remove GeoJSON related functionality from future releases, so there are no property descriptions and no plans to add them.
