### ISSUE TITLE
Креш на симуляторе iOS 16.1 на XCode 14.1

### ISSUE THREAD

**Issue by OneSman7** [yandex/mapkit-ios-demo#174]
Сделал как указано в документации

`На эмуляторе под M1 не поддерживается OpenGL, поэтому в конструкторы YMKMapView и YMKPanoView необходимо передавать vulkanPreferred: true. Эта настройка требуется только для сборки под эмулятор.`

Получаю на симуляторе iOS 16.1 креш при старте. Если отключить vulkan, все ОЧЕНЬ тормозит, но не падает и работает.
На симуляторе iOS 15.2 креша нет. Версии системы ниже не проверял.

<img width="962" alt="Снимок экрана 2022-11-10 в 14 15 56" src="https://user-images.githubusercontent.com/4619076/201077296-e2c7dc55-8255-4ea7-8a28-3d318fb30a60.png">

**Comment by Buxlan** [comment]
Присоединяюсь.
У меня та же проблема при запуске на реальном устройстве, xCode 14.1, MacOS Ventura 13.0

**Comment by Curshet** [comment]
Аналогично. Подтверждаю.

iOS 15.2 (симулятор и девайсы) -> краш отсуствтует, всё, что выше (симуляторы) -> краш.

**YMK_YRTViewRend (53): EXC_BAD_ACCESS (code=1, address=0x7fc55b4e1b70)**

**Comment by mishurov** [comment]
Та же проблема. @Curshet нашли решение?

**Comment by ageevvalentin** [comment]
**YMK_YRTViewRend: EXC_BAD_ACCESS** Ловим на симуляторах при определенных размерах MapView, возможно какие-то проблемы с вычислением размера буфера в OpenGL. Например при размерах 101.5 на 101.5 будет краш, а при размерах 32 на 32 его нет. При этом если отрендерить карту в размерах 32 на 32, то потом уже можно ставить любые размеры на любых новых инстансах и все будет работать нормально.

**Comment by ageevvalentin** [comment]
> Аналогично. Подтверждаю.
> 
> iOS 15.2 и ниже (симулятор/девайс) -> краш отсутствует. Xcode 13.2.1, iOS 15.4 (до iOS 16.1, симуляторы) -> краш при запуске экрана карты. Но... Xcode 14.1, iOS 16.1 (симулятор) -> краш отсутствует (что странно). Предложенные в тикетах решения не помогают.
> 
> **YMK_YRTViewRend (53): EXC_BAD_ACCESS (code=1, address=0x7fc55b4e1b70)**
> 
> <img alt="Снимок экрана 2022-11-29 в 04 54 00" width="1288" src="https://user-images.githubusercontent.com/76473178/204423260-b28aca52-2142-4224-97bd-70e402d5f307.png">

YMK_YRTViewRend: EXC_BAD_ACCESS Ловим на симуляторах при определенных размерах MapView, возможно какие-то проблемы с вычислением размера буфера в OpenGL. Например при размерах 101.5 на 101.5 будет краш, а при размерах 32 на 32 его нет. При этом если отрендерить карту в размерах 32 на 32, то потом уже можно ставить любые размеры на любых новых инстансах и все будет работать нормально. Также помогает более поздний вызов onStart()

**Comment by mishurov** [comment]
@ageevvalentin Яндексу просто надо на Метал переписать карту, она и в симуляторе быстрее будет, т.к. OpenGL софтверно эмулируется, а Метал на железе.

**Comment by ageevvalentin** [comment]
Мы пока решили проблему установкой не векторных карт для симуляторов

**Comment by YandexMapKit** [comment]
Ситуацию с поддержкой Vulkan исправили в последней версии MapKit 4.8.0.
