### ISSUE TITLE
Когда будет поддержка spm? 

### ISSUE THREAD

**Issue by tuo0hym4w** [yandex/mapkit-ios-demo#178]

**Comment by tuo0hym4w** [comment]
Потратил целый день своей жизни и так и не смог собрать пакет на основе YandexMapsMobile.xcframework из внутренностей Pods, постоянно что-то не так. Почему в библиотеке такоего уровня нет нативной поддержки?

**Comment by ARGAMX** [comment]
я смог установить через SPM с этой репы
https://github.com/thematver/YandexMapsMobile.git

**Comment by tuo0hym4w** [comment]
Я видел ее) Немного стремно юзать чужой код 😏 И там под копотом библиотека минимальная, а мне нужна full. Сам пытался так же собрать на своем же репозитории, чтобы тянуть, увы и ах, но не вышло

**Comment by Roman-Kerimov** [comment]
Я, конечно, понимаю, что ещё даже год не прошёл с открытия этого issue, но, команда фреймворка, хоть намекните, пожалуйста, есть ли такие планы.

**Comment by YandexMapKit** [comment]
Такие планы есть, но конкретных сроков назвать мы не можем.

**Comment by ARGAMX** [comment]
@YandexMapKit а почему тогда закрыто как completed?

**Comment by Roman-Kerimov** [comment]
Сейчас подучат алгоритмы, пройдут собес, а там уже можно будет и фреймворком наконец‐то заняться. Может даже на Swift его переписать, и тогда поддержка SPM будет прямо из коробки

**Comment by Oleg-E-Bakharev** [comment]
2 года уже интересуюсь, и "всё никаких четких сроков". Видать не могут свои карты собрать под M1 ARM64-ios simulator.
