### ISSUE TITLE
Можно ли принудительно влиять на порядок отображение пинов, если один из пинов перекрывает другой?

### ISSUE THREAD

**Issue by antoxapa** [yandex/mapkit-ios-demo#179]
Есть два пина с кастомной картинкой, которые находятся достаточно рядом друг с другом и один перекрывает другой.
В картах видна логика, что если один находится чуть ниже другого по координатам, то отображается нижний на первом плане.

Есть ли возможность, к примеру, при тапе на задний пин, отображать его поверх рядом стоящего (выдвигать на передний план)?

**Comment by teshca** [comment]
Для решения этой задачи нужно использовать свойство zIndex
https://yandex.ru/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/MapObject.html#_8
