### ISSUE TITLE
Placemark animation

### ISSUE THREAD

**Issue by MrJounes** [yandex/mapkit-ios-demo#180]
Как добавить custom анимацию появления/скрытия к placemark при нажатии?

**Comment by YandexMapKit** [comment]
Для создания анимации подойдёт [этот метод](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/lite/Classes/YMKPlacemarkMapObject.html#-useAnimation). Также можно организовать анимацию стандартными средствами iOS. Однако, оба варианта потребуют существенной доработки.
