### ISSUE TITLE
Error for architecture arm64

### ISSUE THREAD

**Issue by DanKamilov** [yandex/mapkit-ios-demo#181]
YandexMapKit error In PROJECT/Pods/YandexMapKit/YandexMapKit.framework/YandexMapKit(arrival_object_metadata.o), section __DATA/__bss has type zero-fill but non-zero file offset file 'PROJECT/Pods/YandexMapKit/YandexMapKit.framework/YandexMapKit' for architecture arm64

YandexMapKit 3.5.0
Xcode 14.2

What to do???

**Comment by YandexMapKit** [comment]
Hello!

If you can, send us a minimal compiled example, that demonstrates the situation. It can be uploaded on https://github.com/, or uploaded to https://disk.yandex.com .

We will try to find a solution.

**Comment by DanKamilov** [comment]
It started yesterday. I don't know why. It appears in our main project and I can't send an example. I already tried to reinstall YandexMapKit.

**Comment by DanKamilov** [comment]
> Hello!
> 
> If you can, send us a minimal compiled example, that demonstrates the situation. It can be uploaded on https://github.com/, or uploaded to https://disk.yandex.com .
> 
> We will try to find a solution.

Why you closed the issue?

**Comment by DanKamilov** [comment]
@YandexMapKit https://betterprogramming.pub/xcode-isnt-supported-under-rosetta-3cf214b34c58
We can't run your mapkit with Rosetta now. What to do!!!
