### ISSUE TITLE
Раздельная кластеризация

### ISSUE THREAD

**Issue by vytimoshenko** [yandex/mapkit-ios-demo#183]
Существует ли возможность создавать точки, которые кластеризуются отдельно?

**Comment by YandexMapKit** [comment]
Уточните, пожалуйста, отдельно от чего должны кластеризоваться точки? Опишите задачу подробней. Если возможно, проиллюстрируйте то поведение, которое вы ожидаете от карты для вашего сценария.

**Comment by vytimoshenko** [comment]
Предположим на карте находятся два типа точек - А и Б. Требуется, чтобы при кластеризации точки типа А объединялись только с точками типа А, образуя кластеры типа А, точки типа Б - в кластеры типа Б. Вот пример реализации этой задачи в Apple Maps, каждый тип точек кластеризуется отдельно:

![SimulatorScreenshot](https://user-images.githubusercontent.com/59799232/230184331-c0097ac6-a2c9-450e-813b-e123c7e3b133.png)

**Comment by teshca** [comment]
можно добавить 2 отдельные коллекции и каждой управлять отдельно
https://yandex.com/dev/maps/mapkit/doc/android-ref/full/com/yandex/mapkit/map/MapObjectCollection.html#addClusterizedPlacemarkCollection-com.yandex.mapkit.map.ClusterListener-
