### ISSUE TITLE
Отображение направления

### ISSUE THREAD

**Issue by aumetov7** [yandex/mapkit-ios-demo#184]
Насколько я понял, направление получают из heading. Меня интересует, как сделать, чтобы иконка поворачивалась

Проект пишется на SwiftUI

Сейчас имею следующий код, конфигурирующий pinPlacemark. Если использовать CompositeIcon, то direction применить не получается, да и в целом у меня это не работает

Буду благодарен за помощь

`       
 let pinPlacemark = view.pin.useCompositeIcon()

        pinPlacemark.setIconWithName("icon",
                                     image: UIImage(named: "location")!,
                                     style: YMKIconStyle(anchor: CGPoint(x: 0.5,
                                                                         y: 0.5) as NSValue,
                                                         rotationType: YMKRotationType.noRotation.rawValue as NSNumber,
                                                         zIndex: 1,
                                                         flat: true,
                                                         visible: true,
                                                         scale: 1,
                                                         tappableArea: nil))

        pinPlacemark.setIconWithName("direction",
                                     image: UIImage(named: "direction")!,
                                     style: YMKIconStyle(anchor: CGPoint(x: 0.5,
                                                                         y: 1) as NSValue,
                                                         rotationType: YMKRotationType.rotate.rawValue as NSNumber,
                                                         zIndex: 1,
                                                         flat: true,
                                                         visible: true,
                                                         scale: 1,
                                                         tappableArea: nil))
`

**Comment by aumetov7** [comment]
@YandexMapKit

**Comment by YandexMapKit** [comment]
Для этого вы можете [задать **placemark**](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Classes/YMKPlacemarkMapObject.html#-setIconWithImagestyle) иконку со стилем, где будет задан **YMKIconStyle.rotationType=[YMKRotationTypeRotate](https://yandex.ru/dev/maps/mapkit/doc/ios-ref/full/Enums/YMKRotationType.html#YMKRotationTypeRotate)** .
