### ISSUE TITLE
Результат поиска Submit не содержит все объекты в заданном окне запроса

### ISSUE THREAD

**Issue by VladimirDev89** [yandex/mapkit-ios-demo#185]
В приложении выполняется поиск объектов организаций по фиксированной строке поиска и на участке карты отображаемом на экране. Ограничение resultPageSize = 10000, тип поиска - YMKSearchType.biz
Получаем результат - отображаем. После приближения карты(или незначительном смещении), выполняем resubmit и получаем новые объекты в точках которые и до этого входили в окно запроса. Некоторые старые точки при этом могут не прийти, несмотря на то что участок карты все еще входит в окно запроса. 

Получается что мы получаем не весь список объектов организации в окне запроса, это ожидаемо?
Нет ли способа гарантировано получить все объекты поиска в окне запроса?

**Comment by YandexMapKit** [comment]
API поиска не создано для выгрузки нашей базы, поэтому мы считаем, что можем ограничивать исходя из продуктовой необходимости “как на картах”

1. Есть внутренние жесткие ограничение на выгрузку по количеству на запрос.
2. Особенность текущего устройства поиска в том, что он может решать, что в зависимости от окна часть результатов можно показывать, а часть нет. Способа получить гарантированно все пока нет.
