### ISSUE TITLE
Не работает построение маршрута MapKit iOS Qt Objective-C

### ISSUE THREAD

**Issue by jerboaengine** [yandex/mapkit-ios-demo#186]
Для построения использую метод requestRoutesWithPoints (YMKDrivingRouter). Должен вернутся результат в лямбда функцию, но она не срабатывает.

```
@interface YandexMapView : YMKMapView
@end

@implementation YandexMapView {
    YMKDrivingRouter* drivingRouter;
    YMKDrivingSession* drivingSession;
}

- (instancetype)init
{
    self = [super init];
    drivingRouter = [[YMKDirections sharedInstance] createDrivingRouter];
    return self;
}

- (void)findRoutes
{
    qDebug() << "findRoutes";
    YMKDrivingDrivingOptions* drivingOptions = [[YMKDrivingDrivingOptions alloc] init];
    YMKDrivingVehicleOptions* vehicleOptions = [[YMKDrivingVehicleOptions alloc] init];

    NSMutableArray<YMKRequestPoint*>* requestPoints = [[NSMutableArray alloc] init];

    YMKPoint* dstPoint = [YMKPoint pointWithLatitude:59.959194
                                           longitude:30.407094];
    YMKPoint* srcPoint = [YMKPoint pointWithLatitude:55.733330
                                           longitude:37.587649];

    [requestPoints addObject:[YMKRequestPoint requestPointWithPoint:srcPoint type:YMKRequestPointTypeWaypoint pointContext:nil]];
    [requestPoints addObject:[YMKRequestPoint requestPointWithPoint:dstPoint type:YMKRequestPointTypeWaypoint pointContext:nil]];

    drivingSession = [drivingRouter requestRoutesWithPoints:requestPoints
                                             drivingOptions:drivingOptions
                                             vehicleOptions:vehicleOptions
                                               routeHandler:^(NSArray<YMKDrivingRoute*>* routes, NSError* error) {
                                                   qDebug() << "findRoutes res";
                                               }];
    qDebug() << "findRoutes end";
}
@end
```

В консоли вижу только:
```
findRoutes
findRoutes end
```
Qt iOS - 5.15.2. MapKit iOS - 4.3.1-full. Xcode - 14.3

ПС. Похожая схема со связкой MapKit Android Qt работает отлично.

**Comment by YandexMapKit** [comment]
Такие логи в консоли ожидаемы, ведь запрос асинхронный. Но через какое-то время ответ должен прийти. Нужно удостовериться, что объект `drivingSession`доживает до момента, когда маршруты приходят с сервера.

**Comment by jerboaengine** [comment]
асинхронный это понятно. ожидаю видеть 
findRoutes
findRoutes end
findRoutes res

но последний никогда не срабатывает.
"удостовериться, что объект drivingSession доживает" - как это можно вясянить? отладчиком смотрю он не пустой спустя минуту или две. в демо сборке ипользуется swift(проверил, там с маргрутами все ок). примеров правильного использования под Objective-C не нашел, в документации только небольшие кусочки кода приведены. есть ли где-то демка под Objective-C с построением маршрута?

**Comment by jerboaengine** [comment]
вопрос все еще актуален

**Comment by VladSheremet** [comment]
Столкнулся с этой же проблемой.  @YandexMapKit  помогите решить пожалуйста

**Comment by YandexMapKit** [comment]
Можем предложить следующий вариант решения — не вызывать всё в QML. В основном файле проекта вызвать инициализацию MapKit, построение маршрута (соответствующие функции Objective-C) и сохранить сессию. Затем вызвать QApplication. 

Полагаем, что функции вызываются не в нужном потоке, но если вызвать их из главного потока, то построение маршрута может сработать. Проверьте, пожалуйста, и расскажите, помогло ли это?

**Comment by YandexMapKit** [comment]
В вашем случае получается, что **routeHandler** хранится по **weak** ссылке, в приложении нужно явно в переменную сохранить коллбэк.

**Comment by jerboaengine** [comment]
@YandexMapKit я пробовал вариант хранить колбэк в переменой. так тоже не работает.

**Comment by jerboaengine** [comment]
@YandexMapKit гениально, вы закрыли ветку не решив проблему )
