### ISSUE TITLE
Добавление кастомного layer на objective-c 

### ISSUE THREAD

**Issue by shimprog** [yandex/mapkit-ios-demo#187]
Нет ли примера под objective-c с кастомным слоем, так как с swift получилось добавить, а вот на obj-c не хватает знаний.

Пример из swift
class CustomLayerViewController: BaseMapViewController {

    var layer: YMKLayer?

    internal class CustomTilesUrlProvider: NSObject, YMKTilesUrlProvider {
        func formatUrl(with tileId: YMKTileId, version: YMKVersion) -> String {
            return "https://api.mapbox.com/v4/mapbox.satellite/\(tileId.z)/\(tileId.x)/\(tileId.y)@2.jpg90?access_token=КЛЮЧ_ОТ_MAPBOX";
        }
    }
    let tilesUrlProvider = CustomTilesUrlProvider()
    let projection = YMKProjections.sphericalMercator()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        mapView.mapWindow.map.mapType = YMKMapType.vectorMap;

        let layerOptions = YMKLayerOptions(
            active: true,
            nightModeAvailable: true,
            cacheable: true,
            animateOnActivation: true,
            tileAppearingAnimationDuration: 0,
            overzoomMode: .enabled,
            transparent: false
        )

        layer = mapView.mapWindow.map.addLayer(
            withLayerId: "mapkit_logo",
            contentType: "image/jpeg",
            layerOptions: layerOptions,
            tileUrlProvider: tilesUrlProvider,
            imageUrlProvider: YMKImagesDefaultUrlProvider(),
            projection: projection)

        layer!.invalidate(withVersion: "0.0.0")
    }
}

**Comment by YandexMapKit** [comment]
Примеров на **Objective-C** нет и не планируется, поэтому что-то посоветовать вам не сможем. В ближайшем будущем примеры будут в основном ориентированные на **Swift**.
