### ISSUE TITLE
Не вызывается  responseHandler у метода submit() в версии 4.2.2

### ISSUE THREAD

**Issue by EvgeniyUskov** [yandex/mapkit-ios-demo#189]
Не вызывается responseHandler у метода
func submit(
     with point: [YMKPoint](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKPoint),
     zoom: NSNumber?,
     searchOptions: [YMKSearchOptions](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKSearchOptions),
     responseHandler: @escaping [YMKSearchSessionResponseHandler]
) -> [YMKSearchSession]
Версия библиотеки 4.2.2
С сессией все ок
Объект MapKit создается в AppDelegate в методе didFinishLaunchingWithOptions
Добавление строки YMKMapKit.sharedInstance().onStart() куда бы то ни было не помогает

**Comment by YandexMapKit** [comment]
Увы, без примера не получится разобраться. Пришлите минимальный собранный пример, демонстрирующий описанную ситуацию. Можно выложить его проектом на **[GitHub](https://github.com/)**, прикрепить к переписке **в архиве** или загрузить на **[Яндекс Диск](https://disk.yandex.ru/)** и указать ссылку.

**Comment by DevArtistIOS** [comment]
Создается менеджер
private var searchManager = YMKSearch.sharedInstance()?.createSearchManager(with: .online)

вызывается метод 
searchManager?.submit(with: point, zoom: zoom, searchOptions: searchOptions, responseHandler: responseHandler)
Мы отдаем ему все параметры необходимые, но YMKSearchSessionResponseHandler не отдает ответ после обработки, ничего не происходит больше
При перемещении по карте вызывается метод submit, но вот ответа от него не приходит

(lldb) p searchManager
(YMKSearchManager?) $R16 = 0x000060000337f080 {
  baseNSObject@0 = {
    isa = YMKSearchManager
  }
}

p searchOptions
(YMKSearchOptions) $R15 = 0x00006000069d8c40 {
  baseNSObject@0 = {
    isa = YMKSearchOptions
  }
  _geometry = false
  _disableSpellingCorrection = false
  _searchTypes = 1
  _resultPageSize = 0x0000000000000000
  _userPosition = 0x0000000000000000
  _origin = 0x0000000000000000
  _filters = 0x0000000000000000
}

Как решить проблему с тем, чтобы возвращался ответ в клоужер YMKSearchSessionResponseHandler

**Comment by YandexMapKit** [comment]
Проблема заключается в том, что нужно явно хранить объект responseHandler. Подробнее об этом вы можете посмотреть в нашей [документации](https://yandex.ru/dev/mapkit/doc/ru/ios/quickstart#work)
