### ISSUE TITLE
Использование бэка как посредник для поставноки API ключа 

### ISSUE THREAD

**Issue by tsomaev** [yandex/mapkit-ios-demo#191]
Идея в следующем, мы не хотим держать АПИ ключ на фронте (в мобилке), и хотим использовать наш бэк как посредник для запросов. 

Можно ли реализовать такую логику что запросы от SDK будут идти на бэк, на бэке запрос подписывать ключом (api key) и так отправлять дальше ?

**Comment by tsomaev** [comment]
и так же, я увидел что ест ограничения для АПИ ключа по ID приложении (в случаи iOS это bundle id), решил протестировать, карты работают и в других приложениях (с отличными от указанной мной в админ панели id приложения). 

Нужно подождать или что ?

**Comment by YandexMapKit** [comment]
Активация настроек имеет задержку до 15 минут. Если ключ все еще работает в других приложениях, напишите нам в поддержку по адресу: maps-api@support.yandex.ru. 

Что касается реализации логики, которую вы описали — к сожалению, такой возможности нет

**Comment by tsomaev** [comment]
@YandexMapKit то есть единственный способ защитить ключ - это прописывать bundle id приложения для ключа в админ панели ?
