### ISSUE TITLE
(воссоздано)Не работает построение маршрута MapKit iOS Qt Objective-C

### ISSUE THREAD

**Issue by jerboaengine** [yandex/mapkit-ios-demo#192]
К сожалению мою втеку закрыли. https://github.com/yandex/mapkit-ios-demo/issues/186 
Но вопрос так и не решен. Все советы уважаемого @YandexMapKit  я так или иначе уже пробовал. Проблему это не решило. 

Продублирую закрытый вопрос:
> Для построения использую метод requestRoutesWithPoints (YMKDrivingRouter). Должен вернутся результат в лямбда функцию, но она не срабатывает.
> 
> ```
> @interface YandexMapView : YMKMapView
> @end
> 
> @implementation YandexMapView {
>     YMKDrivingRouter* drivingRouter;
>     YMKDrivingSession* drivingSession;
> }
> 
> - (instancetype)init
> {
>     self = [super init];
>     drivingRouter = [[YMKDirections sharedInstance] createDrivingRouter];
>     return self;
> }
> 
> - (void)findRoutes
> {
>     qDebug() << "findRoutes";
>     YMKDrivingDrivingOptions* drivingOptions = [[YMKDrivingDrivingOptions alloc] init];
>     YMKDrivingVehicleOptions* vehicleOptions = [[YMKDrivingVehicleOptions alloc] init];
> 
>     NSMutableArray<YMKRequestPoint*>* requestPoints = [[NSMutableArray alloc] init];
> 
>     YMKPoint* dstPoint = [YMKPoint pointWithLatitude:59.959194
>                                            longitude:30.407094];
>     YMKPoint* srcPoint = [YMKPoint pointWithLatitude:55.733330
>                                            longitude:37.587649];
> 
>     [requestPoints addObject:[YMKRequestPoint requestPointWithPoint:srcPoint type:YMKRequestPointTypeWaypoint pointContext:nil]];
>     [requestPoints addObject:[YMKRequestPoint requestPointWithPoint:dstPoint type:YMKRequestPointTypeWaypoint pointContext:nil]];
> 
>     drivingSession = [drivingRouter requestRoutesWithPoints:requestPoints
>                                              drivingOptions:drivingOptions
>                                              vehicleOptions:vehicleOptions
>                                                routeHandler:^(NSArray<YMKDrivingRoute*>* routes, NSError* error) {
>                                                    qDebug() << "findRoutes res";
>                                                }];
>     qDebug() << "findRoutes end";
> }
> @end
> ```
> 
> В консоли вижу только:
> 
> ```
> findRoutes
> findRoutes end
> ```
> 
> Qt iOS - 5.15.2. MapKit iOS - 4.3.1-full. Xcode - 14.3
> 
> ПС. Похожая схема со связкой MapKit Android Qt работает отлично.

**Comment by YandexMapKit** [comment]
На данный момент платформа Qt не поддерживается.

2023-07-24 11:37:21, jerboaengine <devnull@yandex.ru>:
> К сожалению мою втеку закрыли. https://github.com/yandex/mapkit-ios-demo/issues/186 
> Но вопрос так и не решен. Все советы уважаемого @YandexMapKit  я так или иначе уже пробовал. Проблему это не решило. 
> 
> Продублирую закрытый вопрос:
>> Для построения использую метод requestRoutesWithPoints (YMKDrivingRouter). Должен вернутся результат в лямбда функцию, но она не срабатывает.
>> 
>> ```
>> @interface YandexMapView : YMKMapView
>> @end
>> 
>> @implementation YandexMapView {
>>     YMKDrivingRouter* drivingRouter;
>>     YMKDrivingSession* drivingSession;
>> }
>> 
>> - (instancetype)init
>> {
>>     self = [super init];
>>     drivingRouter = [[YMKDirections sharedInstance] createDrivingRouter];
>>     return self;
>> }
>> 
>> - (void)findRoutes
>> {
>>     qDebug() << "findRoutes";
>>     YMKDrivingDrivingOptions* drivingOptions = [[YMKDrivingDrivingOptions alloc] init];
>>     YMKDrivingVehicleOptions* vehicleOptions = [[YMKDrivingVehicleOptions alloc] init];
>> 
>>     NSMutableArray<YMKRequestPoint*>* requestPoints = [[NSMutableArray alloc] init];
>> 
>>     YMKPoint* dstPoint = [YMKPoint pointWithLatitude:59.959194
>>                                            longitude:30.407094];
>>     YMKPoint* srcPoint = [YMKPoint pointWithLatitude:55.733330
>>                                            longitude:37.587649];
>> 
>>     [requestPoints addObject:[YMKRequestPoint requestPointWithPoint:srcPoint type:YMKRequestPointTypeWaypoint pointContext:nil]];
>>     [requestPoints addObject:[YMKRequestPoint requestPointWithPoint:dstPoint type:YMKRequestPointTypeWaypoint pointContext:nil]];
>> 
>>     drivingSession = [drivingRouter requestRoutesWithPoints:requestPoints
>>                                              drivingOptions:drivingOptions
>>                                              vehicleOptions:vehicleOptions
>>                                                routeHandler:^(NSArray<YMKDrivingRoute*>* routes, NSError* error) {
>>                                                    qDebug() << "findRoutes res";
>>                                                }];
>>     qDebug() << "findRoutes end";
>> }
>> @end
>> ```
>> 
>> В консоли вижу только:
>> 
>> ```
>> findRoutes
>> findRoutes end
>> ```
>> 
>> Qt iOS - 5.15.2. MapKit iOS - 4.3.1-full. Xcode - 14.3
>> 
>> ПС. Похожая схема со связкой MapKit Android Qt работает отлично.
>
