### ISSUE TITLE
Как анимировать вью у маркера?

### ISSUE THREAD

**Issue by tsaidov7** [yandex/mapkit-ios-demo#193]
Необходимо обновить UIView у уже добавленного на карту маркера при его нажатии.
Устанавливаю в маркер кастомную вью iconView следующим образом.
```
guard let viewProvider = YRTViewProvider(uiView: iconView) else {
   return
}

placemark.setViewWithView(viewProvider, style: style)
```
Подскажите, пожалуйста, как можно это сделать анимировано? Было бы хорошо ряд примеров с различными вариантами решения данного вопроса…

**Comment by tsaidov7** [comment]
Обновить вью/иконку плюс-минус так, как в ЯндексКартах.

https://github.com/yandex/mapkit-ios-demo/assets/37248555/fc1fceae-402d-4ab3-af35-be37da08e4ed

**Comment by YandexMapKit** [comment]
Пример реализации анимации, вы можете посмотреть в MapKit Demo: [github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/MapObjectsViewController.swift#L188](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/MapObjectsViewController.swift#L188).
