### ISSUE TITLE
Ошибка VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT при переиспользования карты на нескольких контроллеров  

### ISSUE THREAD

**Issue by tsomaev** [yandex/mapkit-ios-demo#194]
У меня такой кейс что есть базовый класс **BaseMapViewController**, в котором идет инициализация карты (установку делаю вызовом метода `YMKMapKit.sharedInstance().onStart()` так как они используются в качестве модуля), и есть несколько экранов где показываются карты, и все они наследуются **BaseMapViewController**, это сделано в целях оптимизации, чтобы на каждый экран не создавать новые 

Сам `YMKMapView()` я вынес в отдельный класс, условно в **MapKitBaseView**, и использую как синглтон (или регистрирую в Swinject)

Проблема возникает тогда, когда я, к примеру от **MainMapViewController** перехожу в **HistoryMapViewController**, и после делаю POP, то есть возвращаюсь к **MainMapViewController**, карты на 1-м экране исчезают со следующей ошибкой (не fatalError)

```
[mvk-info] Created 3 swapchain images with initial size (1179, 2248) and contents scale 3.0 for screen Main Screen.

[76256:7047259] kwpL23U0dFSmJ3sD3wir <warn>: Image with VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT allocated
[76256:7047259] kwpL23U0dFSmJ3sD3wir <warn>: Image with VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT allocated
[76256:7047259] kwpL23U0dFSmJ3sD3wir <warn>: Image with VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT allocated
```

после делаю обратно переход к 2-му экрану и там они прекрасно отображаются, но на 1-м нет, теперь 

в памяти смотрел, он там хранится (скрин добавлю), в единственном экзепмпляре, как и задумывалось, но вот ошибка неожиданная и непонятная, буду рад если подскажете в какую сторону мне смотреть, спасибо! 

<img width="391" alt="Снимок экрана 2023-09-13 в 17 05 21" src="https://github.com/yandex/mapkit-ios-demo/assets/28268405/af2ab595-cd84-4a56-b412-284707404c63">

**Comment by tsomaev** [comment]
и так же хотел уточнить, это нормальная практика что используются одни карты на всех экранах (удаляю и устанавливаю нужные объекты) или на каждый экран создавать новые ?

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/) или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.

**Comment by tsomaev** [comment]
> Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/) или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.

https://github.com/tsomaev/YandexMapVulcanErrorExample - пример с воспроизведением ошибки

**Comment by tsomaev** [comment]
@YandexMapKit есть прогресс в этом вопросе ?

**Comment by YandexMapKit** [comment]
У вас экземпляр карт остаётся на последнем инициализированном экране. Вам необходимо сделать обработчик на возвращение к прошлому экрану, чтобы экземпляр карт туда переносился.

2023-09-19 7:24:54, tsomaev <devnull@yandex.ru>:
> @YandexMapKit есть прогресс в этом вопросе ?
