### ISSUE TITLE
Возможность рисовать polygon на экране

### ISSUE THREAD

**Issue by tsomaev** [yandex/mapkit-ios-demo#195]
Подскажите, есть ли в АПИ инструмент, чтобы пользователи могли рисовать на карте 

На данный момент реализовал такую возможность, использую UIPanGestureRecognizer, но такой вариант не совсем посчитал корректным так как собираются все координаты в моменте рисования, на небольшой круг к примеру в массиве хранилось 600 точек координат, здесь мне либо придется форматировать и брать точки смотря на дистанцию или с интервалом 

но прежде чем начну писать костыли, хотелось бы узнать, есть ли такой метод под капотом у карт или нету

**Comment by YandexMapKit** [comment]
[Встроенный редактор](https://yandex.ru/dev/maps/jsbox/2.1/polygonEditor) есть у Яндекса только в JS API версии 2.1.
MapKit под капотом подобных методов не имеет. Реализовать только самостоятельно.
