### ISSUE TITLE
crash on adding more than 4000 placemarks

### ISSUE THREAD

**Issue by Aharonik1** [yandex/mapkit-ios-demo#197]
I'm adding placemarks to map with custom uiimage which rendered using UIGraphicsBeginImageContextWithOptions. is there any optimal solution?

**Comment by YandexMapKit** [comment]
If you can, send us a minimal compiled example, that demonstrates the situation. It can be uploaded on [GitHub](https://github.com/), attached to mail as an archive, or uploaded to [Yandex Disk](https://disk.yandex.com/) and sent to us via link.

We will try to find a solution.

**Comment by Aharonik1** [comment]
thanks for your response. it looks like memory issue. when I was trying to show all placemarks, memory becomes filled. 
to fix issue I used showing only `visible rect`'s placemarks.
