### ISSUE TITLE
Отображение направления устройства пользователя

### ISSUE THREAD

**Issue by IvanBogdantsev** [yandex/mapkit-ios-demo#198]
Добрый день, 

Спасибо за отличный SDK, однако не могу сказать того же по количеству документации, которую вы предоставили. 

Подскажите, пожалуйста, как указывать направления движения пользователя? Если это нужно делать вручную через апдейты менеджера геолокации - подскажите как, если это делается автоматически (как у Мапбокса, Гугла или нативных карт), то... то тоже подскажите как. 

Заранее спасибо

**Comment by YandexMapKit** [comment]
Получите [LocationManager](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/MapKit#createlocationmanager) и подпишитесь в нём на [обновления](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/location/LocationManager#subscribeforlocationupdatesdouble-long-double-boolean-filteringmode-locationlistener). В локациях есть [направление](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/location/Location#getheading).

**Comment by IvanBogdantsev** [comment]
@YandexMapKit и что делать с этим потом? вы можете прямо здесь пример расписать, в документации же ничего нет
