### ISSUE TITLE
Возможно ли детектить тап на станцию метро ? 

### ISSUE THREAD

**Issue by tsomaev** [yandex/mapkit-ios-demo#199]
К примеру хочу получить какую-то информацию о метро, допустим названия, путем тапа на него, но из тех методов что предоставляем api mapkit'a не нашел нужного 

здесь мне придется самому реализовать подобный функционал ? хранить массив координат расположения метро и сравнивая координаты тапа на координаты метро станций что есть у меня ?

**Comment by YandexMapKit** [comment]
Подпишитесь на [события нажатий](https://yandex.ru/dev/mapkit/doc/ru/android/tutorials/map_interaction#taps) по карте. При нажатии получите [Point](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/geometry/Point) с координатами нажатия. С полученными координатами составьте запрос к [API Поиска по организациям](https://yandex.ru/dev/geosearch/doc/ru/) для нахождения информации о метро.
