### ISSUE TITLE
Создать placemark схожий с системным 

### ISSUE THREAD

**Issue by tsomaev** [yandex/mapkit-ios-demo#201]
У MapKit есть такой дизайн при выборе какого-то объекта на карте для placemark 

Можно ли, и если да то как создать подобный placemark, где будет кастомная иконка ? 

<img width="135" alt="Снимок экрана 2023-09-25 в 21 01 19" src="https://github.com/yandex/mapkit-ios-demo/assets/28268405/4efd2736-bce6-4bbf-a2b4-2aa17334af54">

**Comment by YandexMapKit** [comment]
Используйте [ImageProvider](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/runtime/image/ImageProvider) при создании метки. Подробности в [документации](https://yandex.ru/dev/mapkit/doc/ru/android/tutorials/map_with_placemark#display-placemark).

**Comment by tsomaev** [comment]
@YandexMapKit забыл указать что работаю с iOS SDK, и там не нашел такого метода

**Comment by YandexMapKit** [comment]
Для ios тоже возможно использовать [ImageProvider](https://yandex.ru/dev/mapkit/doc/ru/Swift/YRTAnimatedImageProviderFactory) .
[Пример](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/MapObjectsViewController.swift) добавления объектов, включая метки, на карту.
