### ISSUE TITLE
Доступность сервиса

### ISSUE THREAD

**Issue by kryzhikh** [yandex/mapkit-ios-demo#202]
Есть ли возможность отслеживать или проверять вручную доступность сервиса Яндекс Карт? Чтобы, например, в случае недоступности временно переключать пользователя на нативные карты. Нашёл только в YMKOfflineCacheManager возможность подписаться на ошибки, но кажется, что это не совсем то.

**Comment by YandexMapKit** [comment]
У отдельных компонентов есть *listener* — в него придёт ошибка, если будут какие-то проблемы с сетью во время запроса. В общем случае для карты такой возможности нет.

2023-09-25 18:7:0, kryzhikh <devnull@yandex.ru>:
> Есть ли возможность отслеживать или проверять вручную доступность сервиса Яндекс Карт? Чтобы, например, в случае недоступности временно переключать пользователя на нативные карты. Нашёл только в YMKOfflineCacheManager возможность подписаться на ошибки, но кажется, что это не совсем то.
