### ISSUE TITLE
Не отображается stokeColor для CircleView

### ISSUE THREAD

**Issue by tsomaev** [yandex/mapkit-ios-demo#204]
Подскажите, есть код с помощью которого рисуются circleView на картах 

```
let point = YMKPoint(latitude: item.pointCoordinates?.latitude ?? 0.0,
							 longitude: item.pointCoordinates?.longitude ?? 0.0)
		let circle = YMKCircle(center: point, radius: item.radius)
		let strokeColor = item.color.withAlphaComponent(0.8)
		let newPointObject = mapObject.mapObjects.addCircle(with: circle,
															stroke: strokeColor,
															strokeWidth: 0.5,
															fill: item.color.withAlphaComponent(0.1))
		newPointObject.zIndex = 70
		newPointObject.strokeColor = item.color.withAlphaComponent(0.8)
		return newPointObject
```

в основе на всех симуляторах, девайсах, объект отображается, обводка отображается, но почему-то на iPhone 8 Plus, iOS 15.6.1 возникают проблема с отображением обводки 

если нету прозрачности - то проблем нету, но как только добавляю прозрачность - перестает показываться

**Comment by YandexMapKit** [comment]
Описание понятное. Уже решаем вопрос. К сожалению, не могу подсказать по срокам.

**Comment by YandexMapKit** [comment]
В следующем обновлении этот баг больше не должен воспроизводиться. [Следите за новыми версиями в Справке](https://yandex.ru/dev/mapkit/doc/ru/versions).
