### ISSUE TITLE
Игнорируется rotationType в setIconWith()

### ISSUE THREAD

**Issue by pomozoff** [yandex/mapkit-ios-demo#205]
Что `rotationType: YMKRotationType.rotate.rawValue as NSNumber`, что `rotationType: YMKRotationType.noRotation.rawValue as NSNumber`, что `rotationType: nil` - результат один: <img width="559" alt="Screenshot 2023-10-27 at 15 33 41" src="https://github.com/yandex/mapkit-ios-demo/assets/839094/7fafbb9b-cf8f-4fad-a9a4-ea52ed5ea250">

Версия 4.3.1-lite

**Comment by pomozoff** [comment]
`direction` руками высчитывать?

**Comment by pomozoff** [comment]
Ну как обычно, стоило только написать. Решение: `flat: false`

**Comment by StevenKirke** [comment]
Не работает данное решение: flat: false.

**Comment by pomozoff** [comment]
Сочувствую
