### ISSUE TITLE
Удаление маркеров используя метод remove

### ISSUE THREAD

**Issue by AlexGrigorievDev** [yandex/mapkit-ios-demo#208]
Доброго времени.

При удалении маркеров из YMKClusterizedPlacemarkCollection используя метод remove, UI не обновляется.

Метод clear удаляет все точки и UI обновляется

Подскажите нужно как-то дополнительно обновлять ui, или метод remove работает не корректно?

**Comment by teshca** [comment]
как и после добавления, после удаления нужно звать метод clusterplacemarks

https://yandex.ru/dev/mapkit/doc/ru/Objective-C/YMKClusterizedPlacemarkCollection#clusterplacemarkswithclusterradiusminzoom

**Comment by AlexGrigorievDev** [comment]
при добавлении этого метода метки которые не удаляю мерцают так и должно
быть?

ср, 29 нояб. 2023 г. в 21:09, Nickolay Artamonov ***@***.***>:

**Comment by YandexMapKit** [comment]
Сейчас нельзя сделать что бы при пересоздании элементов они не мерцали.
