### ISSUE TITLE
Polyline

### ISSUE THREAD

**Issue by AndrRok** [yandex/mapkit-ios-demo#211]
Подскажите, пожалуйста, как используя массив [YMKPoint] получить polyline(или что-то другое) и сфокусироваться на этой polyline на карте так чтобы все ее точки были видны. Или хотя бы просто сфокусироваться на ее центре? GPT не помог

**Comment by YandexMapKit** [comment]
Вам следует использовать метод [cameraPosition(with:)](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKMap#camerapositionwith)

**Comment by AndrRok** [comment]
А одновременный зум возможен? без отдельного .move
