### ISSUE TITLE
Не устанавливаются обновления до 4.5.0

### ISSUE THREAD

**Issue by SuleymanovKamil** [yandex/mapkit-ios-demo#212]
При попытке обновиться до новых версий или потестить навКит получаю следующую ошибку:
```
[!] CocoaPods could not find compatible versions for pod "YandexMapsMobile":
 In Podfile: 
YandexMapsMobile (= 4.5.0-full)
```

**Comment by YandexMapKit** [comment]
Введите команду **pod repo update**. Если это не поможет, то используйте содержимое Podfile из [демо-репозитория](https://github.com/yandex/mapkit-ios-demo/blob/master/navikit-ios-demo/Podfile).
