### ISSUE TITLE
Вращение иконки пользователя при вращении устройства

### ISSUE THREAD

**Issue by LobanovaViktoria** [yandex/mapkit-ios-demo#215]
Здравствуйте, команда  @YandexMapKit !
Не пойму, что нужно сделать, чтобы иконка пользователя реагировала на изменение направления устройства.
Подскажите, пожалуйста, что я делаю не так?
Прикрепляю архив проекта https://disk.yandex.ru/d/NhQf2nuTz89o5w
Заранее благодарю!

**Comment by YandexMapKit** [comment]
В [UserLocationLayer](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/user_location/UserLocationLayer) не используются показания компаса, направление берётся из GPS данных при движении по маршруту.
Если сценарий требует такое отображение, реализовывать работу с компасом следует самостоятельно.

**Comment by SuleymanovKamil** [comment]
Поддержка у вас, конечно, на высоте. А если пользователь не двигается, но хочет узнать свое направление? Да и дело в том, что иконка не хочет вращаться даже когда задаешь ей direction. Это тоже нужно чинить самостоятельно?
