### ISSUE TITLE
Cannot find 'YMKSearchBusinessPhotoObjectMetadata' in scope

### ISSUE THREAD

**Issue by ilyailyaovch** [yandex/mapkit-ios-demo#217]
Подключил версию библиотеки 4.3.2 к легаси проекту
При использовании класса "YMKSearchBusinessPhotoObjectMetadata" выводиться ошибка "Cannot find 'YMKSearchBusinessPhotoObjectMetadata' in scope".
Яндекс подтвердили что этот класс устарел, но нигде в документации я не нашел аналоги как можно получить метаданные изображений обьекта на карте. Есть ли информация на аналогичные классы или методы в новых версиях библиотеки?

**Comment by YandexMapKit** [comment]
@ilyailyaovch

Сейчас аналогичных классов в MapKit нет. Но в предстоящей версии 4.5.1 снова появится возможность использовать **YMKSearchBusinessPhotoObjectMetadata**. Точной даты релиза этой версии подсказать, увы, не могу.
