### ISSUE TITLE
Время между точками для пешего маршрута

### ISSUE THREAD

**Issue by SuleymanovKamil** [yandex/mapkit-ios-demo#219]
В документации указан пример с YMKDrivingRoute (timeTravelToPoint),  если подобный метод для YMKMasstransitRoute?

**Comment by YandexMapKit** [comment]
@SuleymanovKamil 

У класса [YMKMasstransitRoute](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKMasstransitRoute) нет API, который аналогичен [YMKDrivingRoute](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKDrivingRoute). Поэтому невозможно реализовать функцию [timeTravelToPoint()](https://yandex.ru/dev/mapkit/doc/ru/ios/generated/tutorials/map_routes#time-between-points) для этого класса.
