### ISSUE TITLE
Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found

### ISSUE THREAD

**Issue by MixLxrd** [yandex/mapkit-ios-demo#221]
Добрый день!
Обновил YandexMapMobile с версии 4.3.2 до 4.5.0
При попытке сбилдить проект вылезает ошибка

ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: Undefined symbols:
  _OBJC_CLASS_$_CMMotionActivityManager, referenced from:
       in YandexMapsMobile[arm64][2863](activity_tracker.mm.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Пробовал и под M1 и под розетту

MapKit добавлен через SPM
Подскажите пожалуйста, что можно сделать? (кеш/обновление Xcode/сбросить зависимости уже пробовал)

**Comment by YandexMapKit** [comment]
Здравствуйте!

Попробуйте использовать этот workaround - https://github.com/stripe/stripe-react-native/issues/1532#issuecomment-1807994117.  В случае, если это не поможет, то пришлите, пожалуйста, нам пример приложения. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке в архиве или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку, а также напишите вашу версию Xcode в которой идёт разработка.

2024-02-08 13:38:58, MixLxrd <devnull@yandex.ru>:
> Добрый день!
> Обновил YandexMapMobile с версии 4.3.2 до 4.5.0
> При попытке сбилдить проект вылезает ошибка
> 
> ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
> ld: Undefined symbols:
>   _OBJC_CLASS_$_CMMotionActivityManager, referenced from:
>        in YandexMapsMobile[arm64][2863](activity_tracker.mm.o)
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> Пробовал и под M1 и под розетту
> 
> MapKit добавлен через SPM
> Подскажите пожалуйста, что можно сделать? (кеш/обновление Xcode/сбросить зависимости уже пробовал)

**Comment by Olegnim** [comment]
> Добрый день! Обновил YandexMapMobile с версии 4.3.2 до 4.5.0 При попытке сбилдить проект вылезает ошибка
> 
> ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found ld: Undefined symbols: _OBJC_CLASS_$_CMMotionActivityManager, referenced from: in YandexMapsMobile[arm64][2863](activity_tracker.mm.o) clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> Пробовал и под M1 и под розетту
> 
> MapKit добавлен через SPM Подскажите пожалуйста, что можно сделать? (кеш/обновление Xcode/сбросить зависимости уже пробовал)

Попробуйте настройки Xcode из readme https://github.com/c-villain/YandexMapsMobile?tab=readme-ov-file
Спрятаны под спойлером Latest recommendations for project settings

**Comment by IsaevTA** [comment]
У меня такая-же проблема.
Попробовал оба варианта, не помогает.
