### ISSUE TITLE
Пунктирная отрисовка маршрута YMKMasstransitRoute

### ISSUE THREAD

**Issue by esplusnin** [yandex/mapkit-ios-demo#223]
Здравствуйте

Подскажите пожалуйста, каким образом я могу отрисовать пунктиром пешеходный маршрут YMKMasstransitRoute, что бы визуально это выглядело как пешая навигация в Яндекс. картах?

![IMG_EB5B0A448FCB-1-2](https://github.com/yandex/mapkit-ios-demo/assets/119004420/d079e090-7b3a-4825-9e15-7f7f1574ebd5)

**Comment by YandexMapKit** [comment]
Это можно сделать c помощью [setGapLength](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/PolylineMapObject#setgaplengthfloat).
