### ISSUE TITLE
Как нарисовать произвольную точку использую YandexMapsMobile

### ISSUE THREAD

**Issue by calibrator33** [yandex/mapkit-ios-demo#225]
Как нарисовать касанием произвольную точку на карте Yandex и получить её долготу и широту, используя YandexMapsMobile ? SWIFT

**Comment by YandexMapKit** [comment]
Подпишитесь на [событие нажатия](https://yandex.ru/dev/mapkit/doc/ru/ios/generated/tutorials/map_interaction#taps), считайте координаты и создайте [Метку](https://yandex.ru/dev/mapkit/doc/ru/ios/generated/tutorials/map_objects#placemarks).
