### ISSUE TITLE
Вылетает на iOS 12

### ISSUE THREAD

**Issue by kapitoshka438** [yandex/mapkit-ios-demo#228]
Версия `4.6.1-lite` на девайсе с iOS 12.5.7 вылетает на старте с ошибкой:
```
dyld: Symbol not found: __ZTINSt3__14__fs10filesystem16filesystem_errorE
  Referenced from: /var/containers/Bundle/Application/E76AFDD3-A77F-4DB3-8B77-544B7D7FFD45/Lite.app/Lite
  Expected in: /usr/lib/libc++.1.dylib
 in /var/containers/Bundle/Application/E76AFDD3-A77F-4DB3-8B77-544B7D7FFD45/Lite.app/Lite
```
Опасения начались уже на этапе компиляции:
```
Showing All Issues
Object file (/Users/EMiniakhmetov/Library/Developer/Xcode/DerivedData/MapKitDemo-gpdwumkzdicswoaxpccuuamazvng/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile[4](adler32.c.o)) was built for newer 'iOS' version (13.0) than being linked (12.0)

Object file (/Users/EMiniakhmetov/Library/Developer/Xcode/DerivedData/MapKitDemo-gpdwumkzdicswoaxpccuuamazvng/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/YandexMapsMobile/YandexMapsMobile.framework/YandexMapsMobile[6](crc32.c.o)) was built for newer 'iOS' version (13.0) than being linked (12.0)

и так далее
```
Это баг или намеренно дропнули поддержку iOS 12, но забыли указать в podspec?
С версией `4.5.1-lite` проблем нет.

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный пример вашей ситуации, чтобы мы могли повторить и изучить ошибку на своей стороне. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.

**Comment by kapitoshka438** [comment]
Данный репозиторий и есть минимальный пример, я на нем проверял.

**Comment by kapitoshka438** [comment]
@YandexMapKit получилось ли воспроизвести проблему? Есть ли оценка по срокам, когда сможете исправить?

**Comment by YandexMapKit** [comment]
Уточните, пожалуйста, используемую версию Xcode.

**Comment by kapitoshka438** [comment]
> Уточните, пожалуйста, используемую версию Xcode.

Воспроизводится на Xcode 15.2 и Xcode 15.3

**Comment by YandexMapKit** [comment]
Прошу прощения, в документации была устаревшая информация. Установим новую минимальную версию.
