### ISSUE TITLE
YMKMap возвращает неактуальный YMKVisibleRegion в YMKMapCameraListener

### ISSUE THREAD

**Issue by petropavel13** [yandex/mapkit-ios-demo#23]
Например я хочу приблизить камеру, чтобы кластер распался.
Если я делаю это программно, то я могу получить актуальный YMKVisibleRegion в callback:

```objc
[self.mapView.mapWindow.map moveWithCameraPosition:cameraPosition
                                             animationType:animation
                                            cameraCallback:^(BOOL completed) {
                                                if (completed) {
                                                    // do something with self.mapView.visibleRegion
                                                }
                                            }];
```

Однако, если это делает пользователь, то я могу только слушать события в YMKMapCameraListener и добавлять магическую задержку, чтобы получить актуальный YMKVisibleRegion:

```objc
- (void)onCameraPositionChangedWithMap:(YMKMap *)map
                        cameraPosition:(YMKCameraPosition *)cameraPosition
                    cameraUpdateSource:(YMKCameraUpdateSource)cameraUpdateSource
                              finished:(BOOL)finished {

    if (self.isMapLoaded && finished) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(100 * NSEC_PER_MSEC)), dispatch_get_main_queue(), ^{
            // do something with self.mapView.visibleRegion
        });
    }
}
```

Без задержки:
![ymk_visibleregion_update_no_delay](https://user-images.githubusercontent.com/6436245/51675675-655bd600-1fe5-11e9-9189-6bfb0a475170.gif)

С задержкой 100 мс:
![ymk_visibleregion_update_with_delay](https://user-images.githubusercontent.com/6436245/51675690-786ea600-1fe5-11e9-9747-59d52daae757.gif)

Подскажите пожалуйста, это баг или фича и как с этим работать?

**Comment by realvadim** [comment]
Привет! Тоже с этим столкнулись, кажись все-таки баг) Получается, что нельзя было полагаться на параметр `finished` и тоже пришлось добавлять такую магию =(

**Comment by eberkovich** [comment]
Исправлено в версии 3.3.1.
