### ISSUE TITLE
Ошибка Asset Validation Failed. Invalid MinimumOSVersion

### ISSUE THREAD

**Issue by Torear797** [yandex/mapkit-ios-demo#230]
При загрузке проекта в App Store Connect возникают ошибки (скриншот прикрепил).
Версия MapKit - 4.6.1-full.
Версия Xcode - 15.4
Минимальная версия проекта - iOS 15
В версии Xcode 15.2 такой проблемы нет.
<img width="774" alt="mapKitErrors" src="https://github.com/yandex/mapkit-ios-demo/assets/48101267/534772e3-20ae-44ad-9d06-7623a61fe348">

**Comment by YandexMapKit** [comment]
Спасибо, что рассказали о проблеме. Исправим её в следующем обновлении SDK.

**Comment by kapitoshka438** [comment]
@YandexMapKit это все еще не исправлено
Версия YandexMapKit 4.8.1-lite
Xcode 16.1
