### ISSUE TITLE
Логотип Яндекса при маленьком размере карты

### ISSUE THREAD

**Issue by dmitriykotenko** [yandex/mapkit-ios-demo#232]
При маленьком размере карты (начиная примерно с 100×100) логотип Яндекса смотрится некрасиво: перекрывает значительную часть карты и не влезает по ширине. Ладно бы он был полупрозрачным, но он красно-чёрный с жирным шрифтом:
![YandexMapsIOSSDK-UglyYandexLogo-1](https://github.com/yandex/mapkit-ios-demo/assets/5130336/78994c99-ca60-47a4-a566-2fdbe97a8e72)
![YandexMapsIOSSDK-UglyYandexLogo-2](https://github.com/yandex/mapkit-ios-demo/assets/5130336/9e577e4a-ab46-4bd0-bf27-41fb1162cd3d)

Я могу это исправить установкой огромных отступов:
`ymkMap.logo.setPaddingWith(.init(horizontalPadding: 10_000, verticalPadding: 10_000))`

(При этом `.init(horizontalPadding: .max, verticalPadding: .max)` почему-то уже не срабатывает.)

Но не будет ли это считаться нарушением лицензии?

В идеале для маленьких карт хочется или вообще скрывать логотип, или уменьшать его, чтобы он смотрелся аккуратно и скромно и не перекрывал карту.

**Comment by YandexMapKit** [comment]
Пункт 2.3.8.1 [условий использования сервиса](https://yandex.ru/legal/maps_api/) запрещает двигать, скрывать, видоизменять или перекрывать другими элементами логотип Яндекса на карте. Стоит сделать карту несколько крупнее.

**Comment by dmitriykotenko** [comment]
@YandexMapKit, если двигать запрещено, зачем в СДК функции [YMKLogo.setAlignmentWith()](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKLogo#setalignmentwith_) и [YMKLogo.setPaddingWith()](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKLogo#setpaddingwith_)?

Целью моего поста было, скорее, предложение доработать СДК под маленькие карты, чтобы и на них карта смотрелась красиво. У вас есть, как у Джетбрэйнса, какой-нибудь трэкер, куда можно добавлять предложения по доработкам? Или, может, как-то ещё можно оставить предложение?
