### ISSUE TITLE
Поддержка iOS 12 в версии 4.6.1

### ISSUE THREAD

**Issue by dmitriykotenko** [yandex/mapkit-ios-demo#234]
Верна ли информация из [тикета 228](https://github.com/yandex/mapkit-ios-demo/issues/228) о том, что текущая версия Яндекс-карт (4.6.1) не поддерживает iOS 12? Или это касается только lite-версии?

Недавно обновились на 4.6.1-full, но нам нужна поддержка iOS 12. Сами проверить на девайсах пока не можем.

**Comment by YandexMapKit** [comment]
В 228 тикете информация верна. Мы поддерживаем сборку как lite, так и full версии MapKit **только для 13 версии iOS и выше**.

Сейчас в Справке указана некорректная информация о том, что для стабильной работы подходит 12 версия iOS. Коллеги уже знают об этом, так что эта неточность будет исправлена.
