### ISSUE TITLE
Одновременная поддержка iOS 12 и iOS 17

### ISSUE THREAD

**Issue by dmitriykotenko** [yandex/mapkit-ios-demo#236]
@YandexMapKit, какую версию порекомендуете, если нужна поддержка и iOS 12, и iOS 17?

Версия 4.6.1 [не поддерживает iOS 12.](https://github.com/yandex/mapkit-ios-demo/issues/228) 
Версия 4.5.1 [крэшится при получении GPS-позиции.](https://yandex.ru/dev/mapkit/doc/ru/versions)
Версия 4.5.0 [крэшится в iOS 17.4.](https://yandex.ru/dev/mapkit/doc/ru/versions)

Кажется, что остаётся только версия 4.5.2. Но версия 4.5.2 была выпущена 11 апреля 2024 года — есть подозрения, что она тоже не поддерживает iOS 12.

Или, может быть, есть более ранние версии, которые тоже не крэшатся в iOS 17.4.

Или, может быть, крэш при получении GPS-позиции — это что-то редкое, и можно с ним жить. Но про версию 4.5.1 тоже нет уверенности, что она поддерживает iOS 12.

**Comment by kapitoshka438** [comment]
@dmitriykotenko не знаю про 4.5.2, но мы используем 4.5.1-lite и она точно поддерживает iOS 12. И никаких крэшей при получении GPS у нас нет.

**Comment by dmitriykotenko** [comment]
@kapitoshka438, попробую, спасибо!

**Comment by YandexMapKit** [comment]
Новые версии **MapKit** не поддерживают iOS 12. Мы поддерживаем сборку как lite, так и full версии MapKit **только для 13 версии iOS и выше**. 

Вы можете использовать версию 4.5.1, которая успешно запускается на 17 iOS.
