### ISSUE TITLE
User location

### ISSUE THREAD

**Issue by McFamous** [yandex/mapkit-ios-demo#238]
При первом ините экрана, мне нужно отцентрировать камеру на пользовательской локации. Я нахожу эту точку с помощью: 
`let userLocation = YMKLocationManager.lastKnownLocation()?.position`
Но в случае, когда userlocation = nil, все равно на карте есть метка пользователя. Откуда берутся его координаты?
Доступ к геопозиции разрешен

В каких случаях  `YMKLocationManager.lastKnownLocation()?.position = nil`, кроме того случая, когда нет доступа к геопозиции пользователя?

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный пример вашей ситуации. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.

**Comment by McFamous** [comment]
Для визуализации данного кейса, можно воспользоваться [UserLocationViewController.swift](https://github.com/yandex/mapkit-ios-demo/blob/master/mapkit-demo/MapKitDemo/UserLocationViewController.swift) и в метод viewDidLoad() добавить следующий код:

```
        guard let userLocation = YMKLocationManager.lastKnownLocation()?.position else {
            let alert = UIAlertController(title: nil, message: "Ошибка получения данных локации", preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
            self.present(alert, animated: true, completion: nil)
            return
        }
```

Для большей наглядности ниже предоставлен скриншот, куда добавлен данный код:
![image](https://github.com/yandex/mapkit-ios-demo/assets/55532701/ae8a5499-dbcd-4c9f-abe7-7421065cd3f9)

Как тестировать на симуляторе: 
1. В настройках симулятора Features -> Location -> Custom Location -> ввести свою локацию
2. Открыть UserLocationViewController и дать разрешение на использование геолокации пользователя
3. Выйти из UserLocationViewController
4. В настройках симулятора Features -> Location выбрать None
И при следующем открытии UserLocationViewController вы увидите метку пользователя на карте, а также диалог об ошибке получения данных локации. Откуда берется метка на карте, если данные о локации пользователя отсутствуют?

**Comment by YandexMapKit** [comment]
Если локация не известна, iOS возвращает последнюю известную локацию. Это особенность работы MapKit под iOS.
