### ISSUE TITLE
Пользовательские тайлы

### ISSUE THREAD

**Issue by NickRichter6** [yandex/mapkit-ios-demo#239]
Не очень понятно как работать с TileProvider, есть пример в https://github.com/yandex/mapkit-ios-demo/issues/83
Но все равно не ясно, например: откуда брать baseUrl, разве это не библиотека предоставляет данные о тайлах? и также отсутствует метод addLayer, для создания кастомного layer. Смотрел в примере https://github.com/yandex/mapkit-ios-demo/blob/master/mapkit-demo/MapKitDemo/CustomLayerViewController.swift . И также интересно, есть ли возможность получить id тайлов

**Comment by YandexMapKit** [comment]
[Вопрос](https://github.com/yandex/mapkit-ios-demo/issues/83) был задан пользователем. **baseUrl** может быть адресом хоста, откуда берутся тайлы.

[YMKTilesUrlProvider](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKTilesUrlProvider) используется для форматирования ссылок на пользовательские тайлы. Для получения тайлов стандартной карты вы можете воспользоваться [Tiles API](https://yandex.ru/dev/tiles/doc/ru/).

Добавление производится с помощью [addTileLayer](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKMap#addtilelayerwithlayeridlayeroptionscreatetiledatasource). [Идентификаторами тайлов](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKTileId) являются координаты. То есть с помощью координат можно сформировать идентификатор самостоятельно.

Пожалуйста, опишите ситуацию подробнее, если я понял вас неправильно.
