### ISSUE TITLE
YMKSearchSuggestSession возвращает результат, даже если релевантных подсказок нет.

### ISSUE THREAD

**Issue by kryzhikh** [yandex/mapkit-ios-demo#240]
Здравствуйте!

При поиске саджестов через YMKSearchSuggestSession, если искать что-то заведомо невалидное ("ashfwioufhsak") в ответе всё равно возвращается результат с один айтемом, у которого параметр displayText и некоторые другие равны строке поиска. Однако, по факту релевантных подсказок нет и хотелось бы пользователю показывать пустой список.
Можем ли мы опираться на какие-то параметры ответа, чтобы понимать, что на самом деле подсказок нет, и тот ответ, который пришёл, можно проигнорировать?

**Comment by YandexMapKit** [comment]
Пожалуйста, пришлите нам минимальный пример кода, демонстрирующий ситуацию. Вы можете выложить его проектом на [GitHub](https://github.com/), прикрепить к переписке **в архиве** или загрузить на [Яндекс Диск](https://disk.yandex.ru/) и указать ссылку.

**Comment by kryzhikh** [comment]
[yandex_suggest_sample.zip](https://github.com/user-attachments/files/16125377/yandex_suggest_sample.zip)
@YandexMapKit  прикрепил пример

**Comment by YandexMapKit** [comment]
В SuggestOptions следует явно запрашивать, какой [тип объектов](YMKSuggestType) вы желаете получить:

```
var options = YMKSuggestOptions()
options.suggestTypes = YMKSuggestType.biz // <- HERE
//
suggestSession.suggest(withText: "ashfsalhf", window: .init(southWest: .init(latitude: 55.663353, longitude: 37.450045), northEast: .init(latitude: 55.837971, longitude: 37.713100)), suggestOptions: options)
```

**Comment by kryzhikh** [comment]
@YandexMapKit 
Да, но есть 2 момента
1. Библиотека не обязывает устанавливать значение [suggestTypes](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKSuggestOptions#suggesttypes), если оно не установлено явно, то используется значение определенное на сервере.
2. мне нужны саджесты сразу двух типов, и топонимы и компании, делаю вот так:
```
let options = YMKSuggestOptions()
options.suggestTypes = [.geo, .biz]
```
результат получаю такой же, как если не указывать suggestTypes, т.е. нерелевантную подсказку по поиску "ashfsalhf"
