### ISSUE TITLE
Missing purpose string NSMotionUsageDescription

### ISSUE THREAD

**Issue by dmitriykotenko** [yandex/mapkit-ios-demo#243]
Подключил к своему проекту YandexMapsMobile 4.5.1-full. После загрузки релиза в Апстор-коннект тот ругается: 

> Please correct the following issues and upload a new binary to App Store Connect.
> 
> ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “[my-app].app” bundle should contain a NSMotionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.

@YandexMapKit, подскажите: для чего Яндекс-карты используют CoreMotion? Я не понимаю, что писать в NSMotionUsageDescription.

**Comment by YandexMapKit** [comment]
> Your app’s code references one or more APIs that access sensitive user data

Подскажите, пожалуйста, на какие именно функции ругается Коннект?

**Comment by SuleymanovKamil** [comment]
Написано же два раза - NSMotionUsageDescription

**Comment by dmitriykotenko** [comment]
@YandexMapKit, как и сказал @SuleymanovKamil, коннект ругается на отсутствие NSMotionUsageDescription.

При этом коннект не уточняет, в какой функции вашей библиотеки используется CoreMotion:
«Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access.»

То есть: «Код вашего приложения ссылается на один или несколько АПИ, обращающихся к личным данным пользователя...»

Где именно в вашей библиотеке используется CoreMotion, я не знаю — ваши исходники засекречены.

**Comment by YandexMapKit** [comment]
Ситуация с NSMotionUsageDescription была исправлена в версии 4.5.2, обновитесь до актуальной версии.

**Comment by dmitriykotenko** [comment]
@YandexMapKit, не могу обновиться до 4.5.2, потому что она не поддерживает АйОС 12.

**Comment by dmitriykotenko** [comment]
@YandexMapKit, вы закрыли тикет, не уточнив, подходит ли мне решение. Большое спасибо!
