### ISSUE TITLE
[Переоткрыт] Missing purpose string NSMotionUsageDescription

### ISSUE THREAD

**Issue by dmitriykotenko** [yandex/mapkit-ios-demo#244]
@YandexMapKit, я создал тикет снова — потому что [предыдущий тикет](https://github.com/yandex/mapkit-ios-demo/issues/243) вы преждевременно закрыли, не ответив на вопрос.

На версию 4.5.2 я не могу обновиться, потому что в 4.5.2 вы [убрали поддержку АйОС 12.](https://github.com/yandex/mapkit-ios-demo/issues/236) Придётся жить с версией 4.5.1.

Поэтому мне придётся самому заполнять NSMotionUsageDescription. Поэтому по-прежнему актуален вопрос: для чего YandexMapsMobile использует CoreMotion? Что именно мне указывать в NSMotionUsageDescription?

> Подключил к своему проекту YandexMapsMobile 4.5.1-full. После загрузки релиза в Апстор-коннект тот ругается: 
> 
> > Please correct the following issues and upload a new binary to App Store Connect.
> > 
> > ITMS-90683: Missing purpose string in Info.plist - Your app’s code references one or more APIs that access sensitive user data, or the app has one or more entitlements that permit such access. The Info.plist file for the “[my-app].app” bundle should contain a NSMotionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. If you’re using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. For details, visit: https://developer.apple.com/documentation/uikit/protecting_the_user_s_privacy/requesting_access_to_protected_resources.
> 
> @YandexMapKit, подскажите: для чего Яндекс-карты используют CoreMotion? Я не понимаю, что писать в NSMotionUsageDescription.
>

**Comment by YandexMapKit** [comment]
NSMotionUsageDescription нужен, чтобы автоматически останавливать фоновое ведение, когда пользователь выходит из машины. В публичном MapKit SDK этот датчик не используется, потому мы убрали NSMotionUsageDescription из SDK в последних версиях.
