### ISSUE TITLE
Не вращается Метка при вращении карты.

### ISSUE THREAD

**Issue by StevenKirke** [yandex/mapkit-ios-demo#246]
Подскажите, как вращать метку, Нашел тут ответ (flat: false), но он не рабочий. Сколько не гуглил ни чего не нашел.

![Screenshot 2024-09-17 at 19 39 52](https://github.com/user-attachments/assets/94f6cc27-ab51-4fc8-b3c6-c57646d857c7)

```Swift
	func addPlaceMark(model: MapViewModel.ViewModel.Coordinate) {
		Task.init {
			let point = YMKPoint(latitude: model.latitude, longitude: model.longitude)
			let viewPlacemark = self.mapView.mapWindow.map.mapObjects.addPlacemark(with: point)
			viewPlacemark.setIconWith(
				self.imageMark,
				style: YMKIconStyle(
					anchor: CGPoint(x: 0.5, y: 1) as NSValue,
					rotationType: YMKRotationType.rotate.rawValue as NSNumber,
					zIndex: 0,
					flat: false,
					visible: true,
					scale: 0.5,
					tappableArea: nil
				)
			)
		}
	}
```

**Comment by SuleymanovKamil** [comment]
За вращение отвечает свойство direction, но это не работает через setIconWith. Нужно использовать метод useCompositeIcon(): 

```
viewPlacemark.direction = 90
let compositeIcon = viewPlacemark.useCompositeIcon()
compositeIcon.setIconWithName(
    "pin",
    image: UIImage(избражение для пина),
    style: {
        let iconStyle = YMKIconStyle()
        iconStyle.rotationType = 1
        return iconStyle
    }()
)
```

**Comment by StevenKirke** [comment]
Благодарю за помощь. Попробую реализовать.

**Comment by YandexMapKit** [comment]
Этот метод должен работать штатно, и он представлен в нашем [демонстрационном примере](https://github.com/yandex/mapkit-ios-demo). При этом не нужно указывать **flat** и **rotationType**.

2024-09-19 22:56:22, SuleymanovKamil <devnull@yandex.ru>:
> За вращение отвечает свойство direction, но это не работает через setIconWith. Нужно использовать метод useCompositeIcon(): 
> 
> ```
> viewPlacemark.direction = градус вращения
> let compositeIcon = viewPlacemark.useCompositeIcon()
> compositeIcon.setIconWithName(
>     "pin",
>     image: imageMark,
>     style: {
>         let iconStyle = YMKIconStyle()
>         iconStyle.rotationType = 1
>         return iconStyle
>     }()
> )
> ```

**Comment by SuleymanovKamil** [comment]
> Этот метод должен работать штатно, и он представлен в нашем [демонстрационном примере](https://github.com/yandex/mapkit-ios-demo).

В примерах свойство direction ни разу не используется.
И оно не работает. Должно, но не работает. Как я уже писал в https://github.com/yandex/mapkit-ios-demo/issues/210
