### ISSUE TITLE
Не деинитится вью контроллер на вью которого добавлена YMKMapView на iOS 18

### ISSUE THREAD

**Issue by kryzhikh** [yandex/mapkit-ios-demo#247]
Здравствуйте!

Столкнулись со следующей проблемой: вью контроллер, на вью которого добавлено вью карты YMKMapView не деинитится, когда его больше никто не держит. **Воспроизводится только на iOS 18**

Также при установке фрейма для YMKMapView в консоль выводится сообщение: _Modifying properties of a view's layer off the main thread is not allowed: view <YRTMetalView: 0x106b0e0c0> with nearest ancestor view controller <YandexMapsCheck_iOS18Dealloc.MapViewController: 0x106d18380>_. При этом установка происходит в главной очереди.

Пример проекта, демонстрирующего проблему, прикрепил: 
[YandexMapsCheck_iOS18Dealloc.zip](https://github.com/user-attachments/files/17095536/YandexMapsCheck_iOS18Dealloc.zip)

Шаги:
1. зайти на карту по кнопке
2. уйти с карты
3. принт в деините вью контроллера не вызывается

**Comment by pavelannin** [comment]
+1

**Comment by SelyutinSergey** [comment]
+

**Comment by SuleymanovKamil** [comment]
@YandexMapKit может оставите хотя бы комментарий, что вы увидели проблему?

**Comment by eberkovich** [comment]
Привет,
Уже исправили в ближайшие дни выпустим хотфикс для версии 4.8.0.

**Comment by YandexMapKit** [comment]
Выпустили версию 4.8.1 MapKit, в которой эта проблема исправлена.
