### ISSUE TITLE
YMKUserLocationLayer с CLLocationManager

### ISSUE THREAD

**Issue by SuleymanovKamil** [yandex/mapkit-ios-demo#248]
В проекте я использую нативный CLLocationManager и хочу чтобы иконка пользователя у YMKUserLocationLayer обновлялась по его данным. Как это сделать? 
Если это не возможно, то как мне добиться такого же эффекта как и  setAnchorWithAnchorNormal у YMKUserLocationLayer? То есть я хочу, чтобы камера следовала за пользователем, без использования YMKUserLocationLayer.

**Comment by YandexMapKit** [comment]
Если вы хотите пробрасывать в MapKit SDK свои координаты, нужно использовать [YMKDummyLocationManager](https://yandex.ru/dev/mapkit/doc/ru/Swift/YMKDummyLocationManager). Создайте свой LocationManager и через него передавайте координаты в MapKit.

**Comment by SuleymanovKamil** [comment]
Зачем закрывать ишью, если проблема осталась открытой? 
Мне не нужно пробрасывать свои координаты  в MapKit SDK, меня устраивает и YMKLocationManager. Мне нужно иметь возможность управлять координатами в YMKUserLocationLayer.
