### ISSUE TITLE
Приоритизация пинов на карте с ближайшими координатами

### ISSUE THREAD

**Issue by Olyaashh** [yandex/mapkit-ios-demo#249]
Здравствуйте, можно ли как-то приоритизировать пины по нажатию, есть кластеры пинов маленькие и есть пины Placemark, которые занимают бОльшую область
Если под пином Placemark находится маленький пин, то в методе `onMapObjectTap(with mapObject: YMKMapObject, point: YMKPoint)` передается именно маленький кластер, не смотря на то, что визуально он лежит снизу

и пока не приблизить карту так сильно, чтобы под большим не оказалось маленьких пинов, то нажатие будут перехватывать маленькие точки

Подскажите, пожалуйста, как установить приоритеты?
Или может не приоритеты, а что-то другое, что поможет перехватывать нажатие тем пином, который визуально выше на иерархии вью

**Comment by YandexMapKit** [comment]
Приоритеты объектов на карте можно настраивать с помощью указания значения [zIndex](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/MapObject#getzindex).

2024-10-16 12:38:58, Olyaashh <devnull@yandex.ru>:
> Здравствуйте, можно ли как-то приоритизировать пины по нажатию, есть кластеры пинов маленькие и есть пины Placemark, которые занимают бОльшую область
> Если под пином Placemark находится маленький пин, то в методе `onMapObjectTap(with mapObject: YMKMapObject, point: YMKPoint)` передается именно маленький кластер, не смотря на то, что визуально он лежит снизу
> 
> и пока не приблизить карту так сильно, чтобы под большим не оказалось маленьких пинов, то нажатие будут перехватывать маленькие точки
> 
> Подскажите, пожалуйста, как установить приоритеты?
> Или может не приоритеты, а что-то другое, что поможет перехватывать нажатие тем пином, который визуально выше на иерархии вью

**Comment by Olyaashh** [comment]
меняла значение zIndex(увеличивала), но к сожалению это не помогло, все равно выбирались пины под большим пином

**Comment by Olyaashh** [comment]
[zIndex](https://yandex.ru/dev/mapkit/doc/ru/com/yandex/mapkit/map/MapObject#getzindex) влияет на отрисовку, но при нажатии на пин все равно обработчик в методе onMapObjectTap перехватывает тот пин, который находится снизу

приоритет отображения не равен приоритету, который передается в метод onMapObjectTap

**Comment by Olyaashh** [comment]
@YandexMapKit все же zIndex не помогает с обработчиком нажатия
