### ISSUE TITLE
Программная анимация плейсмарков

### ISSUE THREAD

**Issue by kryzhikh** [yandex/mapkit-ios-demo#253]
Здравствуйте!

Хотим сделать анимацию пульсации для пина пользователя, типа такой
![Запись экрана 2024-11-25 в 17 33 05 (1)](https://github.com/user-attachments/assets/1f27884c-e54b-4a70-819c-0440213b77e9)

Есть ли возможность сделать это программно, например через CoreAnimation на iOS? Или единственный вариант, это через готовую анимацию и YRTAnimatedImageProvider?

**Comment by YandexMapKit** [comment]
Анимацию для пина можно сделать только через **YRTAnimatedImageProvider**.
