### ISSUE TITLE
userLocationLayer - постоянно перекидывает камеру к позиции юзера

### ISSUE THREAD

**Issue by voronoff2803** [yandex/mapkit-ios-demo#26]
userLocationLayer - постоянно перекидывает камеру к позиции юзера.
Можно ли как-то отключить перемещение камеры, что бы спокойно просматривать карту вокруг маркера

**Comment by vbazhenov** [comment]
Можно не вызывать метод setAnchor у userLocationLayer, тогда перекидывать не будет. Или явно позвать resetAnchor, чтобы выйти из режима, где камера следует за пользователем.
