### ISSUE TITLE
Помогите правильно установить свою вью в YMKPlacemarkMapObject

### ISSUE THREAD

**Issue by SlavaIsaev2020** [yandex/mapkit-ios-demo#28]
Привет! 
let viewPopUp = UIView(frame: CGRect(x: 0, y: 0, width: 226, height: 150))
viewPopUp.cornerRadius = 17
viewPopUp.backgroundColor = .white
if let viewProvider = YRTViewProvider(uiView: viewPopUp) {
      placemark.setViewWithView(viewProvider)
}

![screen shot 2019-02-26 at 13 29 47](https://user-images.githubusercontent.com/34311578/53421955-3d4a0300-39e7-11e9-8102-19c78e3d4a05.png)

Не могу никак повлиять на задний ЧЕРНЫЙ ФОН, помогите сделать его прозрачным(

**Comment by realvadim** [comment]
@SlavaIsaev2020 

Вот решение:
view.isOpaque = true
view.backgroundColor = UIColor.clear.withAlphaComponent(0.0)

**Comment by Roman-Kerimov** [comment]
@realvadim, это решение не работает в 4.0.0. В этом случае вообще YMKPlacemarkMapObject не отображается
