### ISSUE TITLE
Как заставить UserLocation слой вращать иконку местоположения пользователя?

### ISSUE THREAD

**Issue by guzhavin** [yandex/mapkit-ios-demo#32]
Правильно ли я понимаю, что нужно установить `userLocationLayer.isHeadingEnabled = false`, добавить слушателя `userLocationLayer.setObjectListenerWith(self)` и в функции ` func onObjectAdded(with view: YMKUserLocationView)` для `view` установить иконку через  `setIconWith`?

**Comment by nexelen** [comment]
Тоже не понимаю как заставить иконку вращать туда куда смотрит юзер. Если userLocationLayer.isHeadingEnabled = false иконка просто будет смотреть на верх

**Comment by sergey-zubkov** [comment]
Данную проблему удалось как-то решить?
Или придется самому отслеживать компас и через  direction у YMKPlacemarkMapObject поворачивать объект?

**Comment by Viveron** [comment]
Есть проблема и с direction у YMKPlacemarkMapObject - поворот не происходит

**Comment by vladislav-m** [comment]
Проблема с direction у YMKPlacemarkMapObject все еще актуально. Версия pod YandexMapsMobile (4.0.0-lite), установка свойства direction никак не влияет на направление иконки на карте. Она всегда смотрит строго наверх.

**Comment by korinviktor** [comment]
Проблема решается выставлением стиля метки.

example.setIconStyleWith(YMKIconStyle(
                anchor: CGPoint(x: 0.0, y: 0.0) as NSValue,
                rotationType: YMKRotationType.rotate.rawValue as NSNumber,
                zIndex: 0,
                flat: true,
                visible: true,
                scale: 1.0,
                tappableArea: nil))
                
//example.direction = 90.0

**Comment by AndrRok** [comment]
Парамаетр flat в YMKIconStyle должен быть false для корректного вращения

> > Проблема решается выставлением стиля метки.
> > example.setIconStyleWith(YMKIconStyle( anchor: CGPoint(x: 0.0, y: 0.0) as NSValue, rotationType: YMKRotationType.rotate.rawValue as NSNumber, zIndex: 0, flat: true, visible: true, scale: 1.0, tappableArea: nil))
> > //example.direction = 90.0
> 
> Извините, а можно подробнее. Я убил целый день но так и не смог повернуть метку.
