### ISSUE TITLE
проблема с func onMapTap

### ISSUE THREAD

**Issue by aposnov** [yandex/mapkit-ios-demo#33]
подскажите пожалуйста вот есть такая функция

func onMapTap(with map: YMKMap, point: YMKPoint) {
print(point.latitude)
print(point.longitude)
}

при клике он как то выборочно показывает координаты, иногда показывает а иногда нет, когда не показывает вот такой в логе UriObjectConverter::convert : No 'name' attribute in object 29479244 in layer mapj

что это означает и как это заставить работать чтобы всегда давал координаты, при любом зуме, когда прям на дом тапаешь?

**Comment by elricbk** [comment]
@eberkovich

**Comment by eberkovich** [comment]
Видимо у вас добавлен GeoObjectTapListener, который возвращает true из onObjectTap, в таком случае при попадании в гео-объект(poi, остановка, дом и т.д.) InputListener.onMapTap уже не вызывается.

**Comment by aposnov** [comment]
Да, так и было. Спасибо за быстрый ответ, теперь все ок :]
