### ISSUE TITLE
метка всегда в центре

### ISSUE THREAD

**Issue by blackFishX** [yandex/mapkit-ios-demo#35]
с помощью какого метода можно сделать, что бы метка всегда была в центре ? сейчас ставлю метку через mapObjects.addPlacemark, но при смещении карты смещается и метка, нужно, что бы метка всегда была в центре и смог получить координаты и название точки , куда попадает метка

**Comment by blackFishX** [comment]
попробовал так :

```
    func onCameraPositionChanged(with map: YMKMap,
                                 cameraPosition: YMKCameraPosition,
                                 cameraUpdateSource: YMKCameraUpdateSource,
                                 finished: Bool) {
        if finished {
            let userLocationLayer = mapView.mapWindow.map.userLocationLayer
            userLocationLayer.resetAnchor()
            
            let point = map.cameraPosition.target
            
            let mapObjects = mapView.mapWindow.map.mapObjects
            mapObjects.clear()
            let placemark = mapObjects.addPlacemark(with: point)
            placemark.setIconWith(UIImage(named: iconsTap)!)
            
           // placemark.isDraggable = true
        }
    }
```

но при перемещении карты метка остается на месте (логично), не подскажите, как сделать, что бы метка даже при перемещении карты была в центре ?

**Comment by eberkovich** [comment]
Mapkit не позволяет привязывать объекты к точке на экране, только к точке на карте.
Для привязки объекта к точке на экране стоит воспользоваться обычными средствами ios sdk: создать view и поместить ее поверх карты в нужной точке.
