### ISSUE TITLE
получение названия из координат YMKPoint

### ISSUE THREAD

**Issue by blackFishX** [yandex/mapkit-ios-demo#36]
Пытаюсь получить название места по координатам

```
    func onSearchResponseName(_ response: YMKSearchResponse) {
        searchPoints.removeAll()
        for searchResult in response.collection.children{
            if let _ = searchResult.obj.geometry.first?.point {

                searchField.text = searchResult.obj.name
            }
        }    
    }
    func getName(point : YMKPoint, zoom : NSNumber){
        let responseHandler = {(searchResponse: YMKSearchResponse?, error: Error?) -> Void in
            if let response = searchResponse {

                self.onSearchResponseName(response)

            } else {
                //  self.onSearchError(error!)
            }
        }
         searchSession = searchManager.submit(with: point, zoom: zoom, searchOptions: YMKSearchOptions(), responseHandler: responseHandler)
    }
```

вызываю так (в методе `onCameraPositionChanged`) :

```
            let point = map.cameraPosition.target
            let zoom = map.cameraPosition.zoom as? NSNumber
            getName(point: point, zoom: zoom!)
```

но в ответ всегда получаю лишь название своей страны

**Comment by blackFishX** [comment]
моя невнимательность, проблему решил взяв первое название из массива  response.collection.children[0].obj.name

**Comment by blackFishX** [comment]
можно ли как-то получить, по возможности, название заведения, если таковое есть - иначе улицу, как и сейчас

**Comment by elricbk** [comment]
Не очень понятно, что имеется в виду под названием заведения, – в условном ТЦ по переданным координатам, может быть 100 организаций. Название какой из них вы хотите получить?

В любом случае, получить организации близкие к переданной точке можно, если в `YMKSearchOptions` передать `searchType = .biz`. То есть первым запросом можно получить информацию об организациях и, если ничего не нашлось, то вторым запросом – информацию о топонимах. За один запрос получить одновременно и организации и топонимы нельзя.
