### ISSUE TITLE
Карта не видит ключ АПИ

### ISSUE THREAD

**Issue by kumold** [yandex/mapkit-ios-demo#37]
View с картой у нас находится в модуле, который загружается в приложение как фреймворк. К сожалению MapKit в модуле не видет ключ, указанный в AppDelegate приложения. Есть ли совет по решению данной проблемы?

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You need to set API key before using MapKit.'`

**Comment by iOSDias** [comment]
@kumold Добрый день, у нас подобная проблема, вы нашли решение?

**Comment by psabrosimova** [comment]
Добрый день! 
Та же проблема: в многомодульном приложении в AppDelegate задаём ключ, в модуле с картами краш с ошибкой про незаданный ключ
Есть у кого-нибудь решение?

**Comment by psabrosimova** [comment]
Похоже, баг с многомодульностью: проблема решилась добавлением пода в модуль с картой и `setApiKey` при инициализации этого модуля

**Comment by creimbord** [comment]
Есть ещё один способ инициализации MapKit в многомодульном приложении. Необходимо после инициализации MapKit'а вызвать у него метод `onStart()`.

Концептуальный пример:
```swift
import YandexMapKit

final class Map {
    var mapKit: YMKMapKit?
 
    init() {
        YMKMapKit.setApiKey("MAPKIT_API_KEY")
        self.mapKit = YMKMapKit.sharedInstance()
        self.mapKit?.onStart()
    }
}
```

**Comment by AlexSuvorov2k** [comment]
Проблема повторяется на debug-сборке на Android

**Comment by YandexMapKit** [comment]
В нашей документации по MapKit рассказали, [как запускать SDK в многомодульном приложении](https://yandex.ru/dev/mapkit/doc/ru/ios/generated/getting_started#provide-key). Попробуйте решение, которое указано в **примечании**.
