### ISSUE TITLE
Программное перемещение карты с затуханием.

### ISSUE THREAD

**Issue by sergey-zubkov** [yandex/mapkit-ios-demo#39]
Здравствуйте! 

Существует необходимость программно переместить карту к заданой координате анимировано, но с затуханием как от жеста "swipe".

Сдвигать анимировано с анимацией из доступных в YMKAnimationType: smooth и linear не получается достичь точно такого же эффекта.

Существует ли возможность такое сделать?

**Comment by eberkovich** [comment]
Здравствуйте,

Нет, кинетическое перемещение реализовано только для жестов.

На стороне приложения можно самостоятельно реализовать нужное кинетическое движение, используя перемещение камеры без анимации.
