### ISSUE TITLE
При установке API ключа вызывает UI Thread из background

### ISSUE THREAD

**Issue by thisisdingo** [yandex/mapkit-ios-demo#44]
`2019-07-22 15:33:08.047418+0300 ------------[2308:409664] yandex::maps::runtime::config::internal::ConfigManagerImpl::ConfigManagerImpl <warn>: Custom experiments are not allowed`
`=================================================================`
`Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 2308, TID: 409661, Thread name: 1#BgNorm(Global, Queue name: com.apple.root.default-qos.overcommit, QoS: 0`
`Backtrace:
2019-07-22 15:33:08.053039+0300 Vodovoz[2308:409661] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 2308, TID: 409661, Thread name: 1#BgNorm(Global, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:`

**Comment by thisisdingo** [comment]
Swift 5.0
Xcode: 10.2.1
Deployment target: 9.0

**Comment by thisisdingo** [comment]
Duplicating
https://github.com/yandex/mapkit-ios-demo/issues/30

**Comment by EmmaVvv** [comment]
Did you solve this issue?

**Comment by thisisdingo** [comment]
@EmmaVvv Not yet. But if something is, I'll let you know)

**Comment by thisisdingo** [comment]
@EmmaVvv I called the method `YMKMapKit.setApiKey(Constants.ApiKeys.yandexMaps)` from the view controller in `viewHasAppeared`. 

Вроде щас все работает

**Comment by EmmaVvv** [comment]
Крашится теперь( 
Эту проблему они должны решить, но почему-то она их не волнует 
Не знаю что теперь делать. На другую карту не могу поменять.. Клиент хочет именно Яндекс

**Comment by thisisdingo** [comment]
@EmmaVvv А что пишет?

**Comment by EmmaVvv** [comment]
Ну классика жанра.. что надо API key заранее задавать 

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'You need to set API key before using MapKit.'

**Comment by EmmaVvv** [comment]
То есть я правильно поняла, ты в апп делегате НЕ вызываешь уже метод 

> .setApiKey
а делаешь это только во вью контроллере, который отображает карту?

**Comment by thisisdingo** [comment]
@EmmaVvv да. Вызываю его в первом открывшемся вью контроллере. Благо у меня экран карты находится далеко.

**Comment by EmmaVvv** [comment]
Ааа, вот почему не крашится) 
Нет, у меня он первый) 
Но спасибо в любом случае

**Comment by georrge1994** [comment]
таккая же проблема на andoird..

**Comment by e60wep** [comment]
Решил проблему добавлением в AppDelegate

`
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        YMKMapKit.setApiKey("myKey")
        return true
    }
`

**Comment by psabrosimova** [comment]
Есть ещё решение в issue https://github.com/yandex/mapkit-ios-demo/issues/37 для проблем с многомодульностью
