### ISSUE TITLE
Отрисовка YMKPolygon под зданиями.

### ISSUE THREAD

**Issue by guzhavin** [yandex/mapkit-ios-demo#47]
Здравствуйте! Не могу понять, почему отрезки линий отрисованные на карте проходят "под зданиями"? Где-то не указал Z-index или проблема в чем-то другом?
Скриншот:
![IMG_2204](https://user-images.githubusercontent.com/26348928/63021699-9be23b00-beba-11e9-9e2b-5bc49fc8b0b6.jpg)
Код:
```
      let polygon = YMKPolygon(outerRing: YMKLinearRing(points: self.points), innerRings: [])
      let polygonMapObject = mapView.mapWindow.map.mapObjects.addPolygon(with: polygon)
      polygonMapObject.fillColor = .green.withAlphaComponent(0.16)
      polygonMapObject.strokeWidth = 3.0
      polygonMapObject.strokeColor = .green

```

**Comment by eberkovich** [comment]
Здравствуйте, 
По умолчанию YMKPolyline и YMKPolygon рисуются под 3d объектами.
Для того, чтобы управлять порядком отрисовки в mapkit есть механизм подслоев. Управление подслоями осуществляется через YMKSublayerManager, создание подслоев для мап объектов: YMKMap::addMapObjectLayer, типы подслоев описаны в YMKSublayer.
ZIndex влияет на расположение объектов в рамках одной подслоя, но не действует между подслоями.

К сожалению, в данные момент в демо приложении нет примера работы с подслоями. Постараемся добавить пример,  сильно не затягивая.

**Comment by eaniconer** [comment]
@guzhavin , пример работы с подслоями добавлен в демо-приложение: пункт `Map Sublayers`.
В примере показано каким образом можно изменить порядок рендеринга подслоев с помощью YMKSublayerManager.
