### ISSUE TITLE
Метод "cameraPositionWithBoundingBox" не вычисляет зум для камеры

### ISSUE THREAD

**Issue by SergeyGamayunov** [yandex/mapkit-ios-demo#49]
Необходимо установить камеру, чтобы она соответствовала группе точек на карте. Вычисление позиции для камеры с помощью метода `cameraPositionWithBoundingBox` возвращает объект, у которого отсутствует значение зума, при попытке установить эту камеру, происходит краш.

Есть ли способ вычислить зум самостоятельно, зная точки, которые должны попасть в камеру?

<img width="880" alt="Screenshot 2019-09-10 at 13 47 26" src="https://user-images.githubusercontent.com/14821368/64607914-22af0880-d3d2-11e9-801a-7b8c7703b031.png">

**Comment by eberkovich** [comment]
Поясните пожалуйста,  что значит отсутствует значение зума?
Есть ли что-нибудь в логе при вызове  cameraPosition(box)?
Что в этот момент выдает MapWindow.width/height?

**Comment by SergeyGamayunov** [comment]
@eberkovich 
Спасибо за наводящие вопросы, проблема была в том, что методы mapWindow width() и heigth() возвращали 0, layoutIfNeeded помог.

**Comment by Michaelsafir** [comment]
Подскажите куда вы поставили layoutIfNeeded - потому что проблема сохраняется по сей день 


> @eberkovich
