### ISSUE TITLE
Suggest // Настройка подсказок 

### ISSUE THREAD

**Issue by PowerRanger2500** [yandex/mapkit-ios-demo#52]
Нужно отображать подсказки при вводе адреса доставки в мобильном приложении. Не могу найти параметры для решения следующих задач:
1. Подсказки должны выводится только в рамках выбранного региона или города
2. Вывод подсказок должен быть только на русском языке
3. Сортировка по удаленности должна производится в зависимости от месторасположения пользователя
4. Было бы здорово сразу также получать координаты

**Comment by elricbk** [comment]
1. Не поддерживается
2. Смена языка/локали работает только на уровне всего MapKit. Если выставлен русский язык, то, по возможности, будет выдаваться на нём. Но это возможно только в случае, когда у объекта есть название на русском.
3. Нужно задавать [`SuggestOptions.userPosition`](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/android/mapkit-search/ref/com/yandex/mapkit/search/SuggestOptions-docpage/)
4. Не поддерживается
