### ISSUE TITLE
Demo Crashes On Click of Map Sublayers

### ISSUE THREAD

**Issue by nirav-kotecha** [yandex/mapkit-ios-demo#53]
After click on Map Sublayers, it will crash app.

**Comment by eaniconer** [comment]
Hi, @nirav-kotecha 

What about other options such as `Map` or `Map Objects`? 

> it will crash app.

Do you have anything related to the crash in device logs?

**Comment by nirav-kotecha** [comment]
Other all objects are working.

**Crash Log :- ** *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'MapSublayers' in bundle NSBundle </Users/elluminatimacpro1/Library/Developer/CoreSimulator/Devices/83FAD98D-8018-490B-A0BB-9EE7DD70866F/data/Containers/Bundle/Application/7AD87712-FD51-478C-814C-59F87BA55460/MapKitDemo.app> (loaded)'

**Comment by nirav-kotecha** [comment]
@eaniconer 

recently, i have create account in yandex and created mapkit key.
but it's not working. map not loading. do you know what's issue going ?
- tested in simulator and device both.

**Comment by eaniconer** [comment]
> recently, i have create account in yandex and created mapkit key.
> but it's not working. map not loading. do you know what's issue going ?

It's known problem. Mapkit key doesn't work at once after it is created. Just wait for 30-45 minutes and it should work.

**Comment by nirav-kotecha** [comment]
@eaniconer it's already 2 hours passed. i have report crash to you that is one hour ago.

**Comment by nirav-kotecha** [comment]
@eaniconer so you have fix this issue and create merge requests ?

**Comment by eaniconer** [comment]
> so you have fix this issue and create merge requests ?

Yes, I've fixed it. 

> it's already 2 hours passed. i have report crash to you that is one hour ago.

Please, create an issue, if the problem with loading the map remains.

**Comment by nirav-kotecha** [comment]
@eaniconer okay thanks. Now, map is load and working.

**Comment by eaniconer** [comment]
@nirav-kotecha , fix merged
