### ISSUE TITLE
YMKMapObjectTapListener example

### ISSUE THREAD

**Issue by tim-po** [yandex/mapkit-ios-demo#6]
I couldn't find any example of object tap listening, neither here, nor anywhere else. It would really help, if you could provide one.

**Comment by remenkoff** [comment]
@tim-po, hi!

maybe it helps:
```swift
mapView.mapWindow.map!.addTapListener(with: self)
```

...tap listener, actually, can be added to any map object:

```swift
placemark.addTapListener(with: self) // YMKPlacemark
```

...and handler:
```swift
extension MyViewController: YMKMapObjectTapListener {
    
    // MARK: - YMKMapObjectTapListener
    func onMapObjectTap(with mapObject: YMKMapObject?, point: YMKPoint) -> Bool {
        guard let placemark = mapObject as? YMKPlacemarkMapObject { return false }
        
        // here you can do what you want to do with tapped placemark
        
        return true
    }
    
}
```

**Comment by kirkitadzenikolozi** [comment]
extension MyViewController: YMKMapObjectTapListener {
    
    // MARK: - YMKMapObjectTapListener
    func onMapObjectTap(with mapObject: YMKMapObject?, point: YMKPoint) -> Bool {
        guard let placemark = mapObject as? YMKPlacemarkMapObject else { return false }
        
        // here you can do what you want to do with tapped placemark
        
        return true
    }
    
}
