### ISSUE TITLE
Cant see map UI ?

### ISSUE THREAD

**Issue by saroar** [yandex/mapkit-ios-demo#62]
![IMG_7832](https://user-images.githubusercontent.com/8770772/72273102-d3583d80-363a-11ea-8d89-7ebeeed20295.PNG)
why i can't see my map? I create an account on Yandex and get API key

**Comment by eaniconer** [comment]
@saroar , Mapkit API key doesn't work at once after it has been created. Just wait for 30-45 minutes and it should work. Check it out again, please.

**Comment by saroar** [comment]
thanks @eaniconer its working now
