### ISSUE TITLE
Не отображается логотип Яндекса на картах

### ISSUE THREAD

**Issue by valnoc** [yandex/mapkit-ios-demo#64]
Ситуация возникает при использовании модуляризации в проекте.
Не отображается логотип Яндекса на картах, если подключать YandexMapKit не напрямую в Application Target, а через модуль (dynamic framework target).

Если подключение выглядит так, то логотип отображается.
- ApplicationTarget
  - YandexMapKit

Если подключение выглядит так, то логотип НЕ отображается.

- ApplicationTarget
  - MapsWrapper.framework
    - YandexMapKit

YandexMapKit (3.4)

**Comment by valnoc** [comment]
похожий issue в андроиде
https://github.com/yandex/mapkit-android-demo/issues/132

**Comment by user1231232131** [comment]
Подключаю через спм, есть идея, что ассеты просто не грузятся от карты, нашли решение?

**Comment by YandexMapKit** [comment]
В [релизе 4.3](https://yandex.ru/dev/maps/mapkit/doc/dg/concepts/versions.html#versions__versions) такое поведение было исправлено.
