### ISSUE TITLE
[Question] Animating Placemarks

### ISSUE THREAD

**Issue by ssaylanc** [yandex/mapkit-ios-demo#67]
Is there a way add animation (bounce) to placemarks?

**Comment by eberkovich** [comment]
You can implement any animation manually changing properties of placemark.

For example:
```
self.movablePlacemarkDisplayLink = [CADisplayLink displayLinkWithTarget:self selector:@selector(pl)];

//...
- (void)movePlacemark
{
    self.pl.geometry = [YMKPoint pointWithLatitude:(self.pl.geometry.latitude + 0.00001) longitude:self.pl.geometry.longitude];
}
```

Also it is possible to use [frame animation](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/ios/mapkit/ref/YMKPlacemarkMapObject-docpage/#method_detail__method_useAnimation).
