### ISSUE TITLE
Неверное сравнение YMKPoint с одинаковыми координатами

### ISSUE THREAD

**Issue by andymedvedev** [yandex/mapkit-ios-demo#77]
Здравствуйте, может кто-нибудь подсказать почему при сравнении `YMKPoint` с одинаковыми координатами выдает `false`?
```
let p1 = YMKPoint(latitude: 50, longitude: 50)
let p2 = YMKPoint(latitude: 50, longitude: 50)
        
print(p1 == p2) // false
```

Так же поэтому не работает следующий код:
```
let set = Set([YMKPoint(latitude: 50, longitude: 50)])
        
print(set.contains(YMKPoint(latitude: 50, longitude: 50)))
```

**Comment by eberkovich** [comment]
Здравствуйте, 

В приведенном Вами примере сравниваются не значения объектов, а ссылки на них, а они действительно разные.
https://docs.swift.org/swift-book/LanguageGuide/ClassesAndStructures.html#ID90
