### ISSUE TITLE
YRTViewProvider отсутсвует прозрачность

### ISSUE THREAD

**Issue by ARGAMX** [yandex/mapkit-ios-demo#78]
YRTViewProvider отсутсвует прозрачность.

YandexMapKit (3.5.0)

    private func refreshOfficesOnMaps(offices: [Office], map: YMKMap) {
        for office in offices {
            if let latitude = Double(office.lat), let longitude = Double(office.lon) {
                let point = YMKPoint(latitude: latitude, longitude: longitude)

                let size = 35.0
                let frame = CGSize(width: size, height: size)
                let rect = CGRect(origin: CGPoint.zero, size: frame)
                let hostView = UIView(frame: rect)
                let buttonView = UIButton(frame: rect)
                //buttonView.addTarget(self, action: buttonPressAction, for: .touchUpInside)
                buttonView.contentMode = .center
                buttonView.setImage(UIImage(named: "officeMapPin2"), for: .normal)
                hostView.addSubview(buttonView)
                hostView.backgroundColor = .clear
                buttonView.backgroundColor = .clear
                hostView.isOpaque = false
                buttonView.isOpaque = false
                if let viewProvider = YRTViewProvider(uiView: hostView) {
                    map.mapObjects.addPlacemark(with: point, view: viewProvider)
                }
            }
        }
    }

Результат:
https://sun1-88.userapi.com/bUcFrgmhVeFYH6uJdRbMBGXk9c3YKEZ252JS3g/45HCKzssVxo.jpg

**Comment by eberkovich** [comment]
Для того, чтобы получить прозрачный фон, нужно у backgroundColor еще позвать withAlphaComponent(0.0)

**Comment by eberkovich** [comment]
Ну точнее у результата clear нужно позвать withAlphaComponent(0).
