### ISSUE TITLE
Как установить отступы у карты?

### ISSUE THREAD

**Issue by melanu1991** [yandex/mapkit-ios-demo#81]
Добрый день. Работаю с iOS mobile sdk, также в приложении существует google map sdk. Вопрос такой, в данный момент видимый контент google map выставляется при помощи padding карты, благодаря чему удается поддержать smooth ui, но в компоненте yandex mapkit не могу найти такого свойства, чтобы можно было управлять видимой областью задавая padding карте. Есть ли такой механизм или планируется он в будущем? Заранее спасибо за ответ.

**Comment by eberkovich** [comment]
Здравствуйте, для этого можно воспользоваться свойством [focusRect](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/ios/mapkit/ref/YMKMapWindow-docpage/#property_detail__property_focusRect)

**Comment by AlexSuvorov2k** [comment]
**Пример кода:**

```
val startX = width / 10
val endX = width - (width / 10)

val startY = 0f
val endY = height - offset.toFloat()
map_view.focusRect = ScreenRect(ScreenPoint(startX, startY), ScreenPoint(endX, endY))
```

Я к этому шёл очень долго))
