### ISSUE TITLE
Как наложить собственные слои/тайлы на карту? 

### ISSUE THREAD

**Issue by Boolkast** [yandex/mapkit-ios-demo#82]
Требуется добавить собственный слой на карту, но я не нашёл документацию по этому вопросу. Подобная процедура описана только под JS, на ios я подобного не обнаружил. Подскажите, пожалуйста, куда копать?

**Comment by eberkovich** [comment]
Вот пример для растрового слоя: https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/CustomLayerViewController.swift

А вот для векторного geojson: https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/GeoJsonViewController.swift
