### ISSUE TITLE
Не правильно определяется положение центра карты при установке focusRect

### ISSUE THREAD

**Issue by evssar** [yandex/mapkit-ios-demo#84]
Здравствуйте.
Устанавливаю focusRect в методе контроллера viewDidLayouSubviews

```
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        let topLeftPoint = YMKScreenPoint(
            x: Float(pinLayoutGuide.layoutFrame.origin.x),
            y: Float(pinLayoutGuide.layoutFrame.origin.y))
        let bottomRightPoint = YMKScreenPoint(
            x: Float(pinLayoutGuide.layoutFrame.size.width) + topLeftPoint.x,
            y: Float(pinLayoutGuide.layoutFrame.size.height) + topLeftPoint.y)
        let focusRect = YMKScreenRect(topLeft: topLeftPoint, bottomRight: bottomRightPoint)

        if mapView.mapWindow.focusRect != focusRect {
            mapView.layoutIfNeeded()
            mapView.mapWindow.focusRect = focusRect
        }
    }
```
После этого в методе `onCameraPositionChanged(
        with map: YMKMap,
        cameraPosition: YMKCameraPosition,
        cameraUpdateSource: YMKCameraUpdateSource,
        finished: Bool
    )` cameraPosition.target (черная точка на рисунке) не соответсвует положению центра focusRect
![Simulator Screen Shot - iPhone 8 - 2020-07-08 at 00 17 46](https://user-images.githubusercontent.com/26201879/86845368-11965d00-c0b2-11ea-9474-483af13b2c6f.png)

**Comment by eberkovich** [comment]
Здравствуйте,

Уточните пожалуйста:
- какой focusRect возвращает mapWindow в onCameraPositionChanged?
- если добавить SizeChangedListener, какие размеры возвращаются в onMapWindowSizeChanged?

**Comment by evssar** [comment]
Размер экрана mapView.frame
```
(0.0, 0.0, 375.0, 667.0)
  ▿ origin : (0.0, 0.0)
    - x : 0.0
    - y : 0.0
  ▿ size : (375.0, 667.0)
    - width : 375.0
    - height : 667.0
```
mapWindow.focusRect в onCameraPositionChanged (совпадают с заданным фреймом)
```
mapView.mapWindow.focusRect?.topLeft.x - 0.0
mapView.mapWindow.focusRect?.topLeft.y - 111.0
mapView.mapWindow.focusRect?.bottomRight.x - 375
mapView.mapWindow.focusRect?.bottomRight.y - 267
```

Размеры возвращаются в onMapWindowSizeChanged:
до вызова mapView.layoutIfNeeded() 
```
mapWindow.width() - 828
mapWindow.height() - 1792
```
после вызова mapView.layoutIfNeeded() 
```
newWidth - 750
newHeight -  1334
```
новые размеры в onMapWindowSizeChanged
```
newWidth - 750
newHeight -  1334
```

**Comment by eberkovich** [comment]
Значит все верно, target рисуется в центре заданного focusRect.
