### ISSUE TITLE
No available cache for request

### ISSUE THREAD

**Issue by AntonBrock** [yandex/mapkit-ios-demo#85]
У меня выходит ошибка при обычном suggest, как я могу очистить его ?

**Comment by elricbk** [comment]
Такая ошибка показывается при использовании комбинированного поиска (онлайн+оффлайн), если нет нужных кэшей для оффлайн-поиска. Чтобы такая ошибка не показывалась, нужно [создавать][1] менеджер, который использует только онлайн-поиск (`YMKSearchSearchManagerType.online`)

[1]: https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/ios/mapkit-search/ref/YMKSearch-docpage/#method_detail__method_createSearchManagerWithSearchManagerType__YMKSearchSearchManagerType

**Comment by Stampoo** [comment]
> Такая ошибка показывается при использовании комбинированного поиска (онлайн+оффлайн), если нет нужных кэшей для оффлайн-поиска. Чтобы такая ошибка не показывалась, нужно [создавать](https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/ios/mapkit-search/ref/YMKSearch-docpage/#method_detail__method_createSearchManagerWithSearchManagerType__YMKSearchSearchManagerType) менеджер, который использует только онлайн-поиск (YMKSearchSearchManagerType.online)

@elricbk Привет, подскажи пожалуйста, а `.combined` разве не подразумевает подобную логику работы(сильно упрощая):

```mermaid
flowchart LR

A(Поиск) --> B{Кеш}
B --> D(Ответ)
B -->  C(Сеть)
C --> D
```
Другими словами говоря, если нету кеша, но есть сетевое соединение, то ответ мы энивей должны получить вместо ошибки в колбеке?(Сейчас это работает, но не во всех случаях, но при этом если падает, то с ошибкой отсутствия кеша)
