### ISSUE TITLE
не отрабатывает responseHandler в suggestSession

### ISSUE THREAD

**Issue by ARDcode** [yandex/mapkit-ios-demo#86]
Добрый день, необходимо было реализовать работу с suggestions в react-native, но handler почему-то не вызывается. В логах ошибок нет. 
Версия либы последняя.
```
- (void) fetchSuggestions:(NSString *)query {
    NSLog(@"%@", query);
    [[NSOperationQueue mainQueue] addOperationWithBlock:^{
        YMKSuggestOptions* options = [YMKSuggestOptions new];
        options.userPosition = false;
        options.suggestTypes = YMKSuggestTypeGeo;
        YMKBoundingBox* boundingBox = [YMKBoundingBox boundingBoxWithSouthWest:[YMKPoint pointWithLatitude:55.55 longitude:37.42] northEast:[YMKPoint pointWithLatitude:55.95 longitude:37.82]];
        YMKSearchSuggestSession *suggestSession = [self->searchManager createSuggestSession];
        [suggestSession suggestWithText:query window:boundingBox suggestOptions:options responseHandler:^(NSArray<YMKSuggestItem *> *suggestItems, NSError *error) {
            if (error) {
                NSLog(@"Error");
            }
            NSLog(@"SUGGESTION");
            NSMutableArray* suggestResult = [[NSMutableArray alloc]init];
            unsigned long suggestionsSize = MIN(5, [suggestItems count]);
            
            for (int i = 0; i < suggestionsSize; i++) {
                [suggestResult addObject:@{@"value": [[suggestItems objectAtIndex:i] displayText]}];
                NSLog(@"%@", [[suggestItems objectAtIndex:i] displayText]);
            }
            
            NSMutableDictionary* resultObject = [[NSMutableDictionary alloc]init];
            [resultObject setValue:suggestResult forKey:@"suggestions"];
        }];
    }];
```

**Comment by elricbk** [comment]
Добрый день. Сессию нужно сохранять в поле класса. Если её сохранить в локальную переменную, то она уничтожится, и запрос отменится.

**Comment by ARDcode** [comment]
> Добрый день. Сессию нужно сохранять в поле класса. Если её сохранить в локальную переменную, то она уничтожится, и запрос отменится.

не помогает (

**Comment by elricbk** [comment]
Получилось что-то вроде

```
self->suggestSession = [self->searchManager createSuggestSession];
[self->suggestSession suggestWithText:query window:boundingBox suggestOptions:options...
```
как в [примере](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/SuggestTableViewController.swift)?

**Comment by ARDcode** [comment]
> Получилось что-то вроде
> 
> ```
> self->suggestSession = [self->searchManager createSuggestSession];
> [self->suggestSession suggestWithText:query window:boundingBox suggestOptions:options...
> ```
> 
> как в [примере](https://github.com/yandex/mapkit-ios-demo/blob/master/MapKitDemo/SuggestTableViewController.swift)?

да, но не работает

**Comment by elricbk** [comment]
Попробуйте тогда `responseHandler` тоже сложить в поле, чтобы клиент держал на него ссылку.

**Comment by ARDcode** [comment]
> Попробуйте тогда `responseHandler` тоже сложить в поле, чтобы клиент держал на него ссылку.

не помогло

**Comment by elricbk** [comment]
А в демо-приложении саджест у вас работает? Если работает, то нужно внутри вашего приложения воспроизвести ту же логику, что и в примере.

Ещё на всякий случай – сессию имеет смысл создать один раз и потом для неё вызывать уже `suggestWithText`.

**Comment by ARDcode** [comment]
> А в демо-приложении саджест у вас работает? Если работает, то нужно внутри вашего приложения воспроизвести ту же логику, что и в примере.
> 
> Ещё на всякий случай – сессию имеет смысл создать один раз и потом для неё вызывать уже `suggestWithText`.

работает отлично, воспроизвожу ту же логику - не работает. Сессия создается один раз. Можете сделать пример рабочий на ObjC? Репозиторий с кодом на ObjC неактивен уже несколько лет.

**Comment by ARDcode** [comment]
само решилось после добавления swift в проект

**Comment by AlexChanov** [comment]
Тот же самый вопрос код скопировал с примера в гх и не работает комплишен
