### ISSUE TITLE
Как получить данные какой тип объекта найден?

### ISSUE THREAD

**Issue by abpopov** [yandex/mapkit-ios-demo#93]
Здравствуйте
Подскажите пожалуйста, как получить что за объект найден

Нам необходимо понять, найден ли адрес с точностью до дома

**Comment by elricbk** [comment]
Нужно посмотреть на компоненты адреса в [YMKSearchToponymObjectMetadata][1]. Если найден дом, то в адресе будет компонент с соответствующим типом (видимо, `YMKSearchComponentKindHouse`).

[1]: https://tech.yandex.ru/maps/mapkit/doc/3.x/concepts/ios/mapkit-search/ref/YMKSearchToponymObjectMetadata-docpage/
