### ISSUE TITLE
Есть ли возможность получения ближайшего дома?

### ISSUE THREAD

**Issue by migonin** [yandex/mapkit-ios-demo#98]
Я получаю адрес координат через этот метод:
```
- (nonnull YMKSearchSession *)submitWithPoint:(nonnull YMKPoint *)point
                                         zoom:(nullable NSNumber *)zoom
                                searchOptions:(nonnull YMKSearchOptions *)searchOptions
                              responseHandler:(nonnull YMKSearchSessionResponseHandler)responseHandler;
```

и метадату `YMKSearchToponymObjectMetadata`. 

Если координаты попали не в дом, а в улицу, есть ли возможность получить ближайший дом? Аналогично передаче `kind: house` в http api?

Спасибо.

**Comment by elricbk** [comment]
Нет, MapKit такую возможность не поддерживает.
