### ISSUE TITLE
Поддержка swift package manager для YandexMapKit

### ISSUE THREAD

**Issue by phoe3nix** [yandex/mapkit-ios-demo#99]
Spm очень быстро развивается и всё большее количество проектов переходит на него. Подавляющее количество библиотек также поддерживают механизм дистрибьюции через spm. Когда для YandexMapKit будет добавлена поддержка spm?

**Comment by SergeySafiullin** [comment]
Поддерживаю. Хотелось бы видеть поддержку SPM

**Comment by phoe3nix** [comment]
я тут подготовил небольшой readme и example проекта, с подключенным YandexMapKit через SPM. В ближайшее время добавлю там скрипт, который всё сделает побыстрее. Но описание полное всего уже есть)
https://github.com/phoe3nix/yandexMapKit-spm-demo

**Comment by SergeySafiullin** [comment]
> я тут подготовил небольшой readme и example проекта, с подключенным YandexMapKit через SPM. В ближайшее время добавлю там скрипт, который всё сделает побыстрее. Но описание полное всего уже есть)
> https://github.com/phoe3nix/yandexMapKit-spm-demo

Спасибо тебе большое!

**Comment by bus16** [comment]
Очень хотелось-бы знать планы переезда на SPM
Есть какие-то прогнозы?)

**Comment by OlegEremenko991** [comment]
Когда планируется переезд на SPM, уважаемые коллеги-разработчики?

**Comment by OlegEremenko991** [comment]
Когда сможете добавить поддержку Swift Package Manager?

**Comment by maksimgromov** [comment]
Есть какие-то обновление по данному вопросу?

**Comment by c-villain** [comment]
с каждым новым Xcode-ом spm все более и более нужен)))

**Comment by maksimgromov** [comment]
Так собрать пакет из кокоаподса не сложно, я эти карты использую в виде пакета, однако, это не решает возникших здесь ошибок.

**Comment by traktor74** [comment]
> Так собрать пакет из кокоаподса не сложно, я эти карты использую в виде пакета, однако, это не решает возникших здесь ошибок.

а как из кокоаподс собрать версию 4.0.0 ?

**Comment by maksimgromov** [comment]
Примерно так - https://habr.com/ru/company/e-legion/blog/549390/

**Comment by maksimgromov** [comment]
> Если кому надо, вот [версия](https://github.com/c-villain/YandexMapsMobile), работающая на Xcode > 13.3 в режиме Розетты, собирается как на девайс, так и на симулятор...

А данный пакет создан для версия яндекс карт 4.0.1 или 4.1.0?

**Comment by Roman-Kerimov** [comment]
Кажется, обновления стали выходить куда чаще, чем это было ранее. Может и поддержку SPM удастся добавить в скором в ремени?

**Comment by ARGAMX** [comment]
Когда планируется добавление поддержки Swift Package Manager в mapkit?

**Comment by ARGAMX** [comment]
я смог установить через SPM с этой репы
https://github.com/thematver/YandexMapsMobile.git

**Comment by c-villain** [comment]
@ARGAMX https://github.com/c-villain/YandexMapsMobile

**Comment by YandexMapKit** [comment]
У нас есть в планах добавить поддержку SPM, но конкретных сроков назвать не можем.

**Comment by Quasaryy** [comment]
Шел 2024 год, как дела с SPM?

**Comment by ARGAMX** [comment]
> У нас есть в планах добавить поддержку SPM, но конкретных сроков назвать не можем.

@YandexMapKit а можно хотя бы этот Issue открыть обратно?..

**Comment by artsuvv** [comment]
@YandexMapKit скоро будет 2025, к нг сделаете?

**Comment by alphatroya** [comment]
А зачем им спешить? Они монополисты, сделают когда задача с дна беклога всплывет. Хотя тут вся работа - скопировать [рабочее](https://github.com/c-villain/YandexMapsMobile), проверенное в продакшене решение стороннего разработчика. Да и зачем делать поддержку официального для Apple менеджера пакетов, юзайте [депрекейтнутый](https://blog.cocoapods.org/CocoaPods-Support-Plans/) Cocoapods.
